### ISSUE TITLE
Add support for XML namespaces

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#194]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 03, 2011 08:16:00_

E.g. 

expect().body("rss.channel.dc:creator", equalTo(""))...

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=39_

**Comment by johanhaleby** [comment]
_From [normanwalsh](https://code.google.com/u/normanwalsh/) on November 14, 2013 15:49:12_

In addition,  this doesn't work. Assuming that namespaceBindings includes a binding for "p", this

  expect().body("/p:foo", namespaceBindings)

should work, but it doesn't. At least if 'foo' is in the default namespace in the document it doesn't work.

**Comment by johanhaleby** [comment]
_From [normanwalsh](https://code.google.com/u/normanwalsh/) on November 14, 2013 16:04:56_

Also, this is a valid expression, with the right bindings:

hasXPath("node-name(/*) = xs:QName('db:package-database')", packageNamespaces)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 15, 2013 03:05:33_

The XPath implementation is provided by Hamcrest, perhaps you could try updating the Hamcrest lib and see if that works any better?

**Comment by johanhaleby** [comment]
_From [normanwalsh](https://code.google.com/u/normanwalsh/) on November 15, 2013 10:11:53_

No change. But I'll see if I can report it back to the Hamcrest folks.

**Comment by johanhaleby** [comment]
_From [normanwalsh](https://code.google.com/u/normanwalsh/) on November 15, 2013 10:24:11_

Hmmm. In the  Hamcrest unit tests, this works:

        assertThat(nsxml, hasXPath("/test:root", bindings));

In rest-assured, this goes bang:

                body(hasXPath("/db:package-database", packageNamespaces)).

java.lang.AssertionError: 1 expectation failed.
Expected: an XML document with XPath /db:package-database 
  Actual: \<?xml version="1.0" encoding="UTF-8"?>
\<package-database xmlns=" http://marklogic.com/manage/package/databases ">
  \<metadata xmlns:db=" http://marklogic.com/manage/package/databases ">
    \<package-version>2.0</package-version>

I wonder if there's something different about the way you setup the context?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 20, 2013 08:50:55_

I've tried implementation support for XPath namespaces in master now. Depend on version 1.8.2-SNAPSHOT after having added the following repo:

\<repositories>
        \<repository>
            \<id>sonatype</id>
            \<url> https://oss.sonatype.org/content/repositories/snapshots/</url> \<snapshots />
        \</repository>
\</repositories>

To use namespaces in XPath you must for configure REST Assured to use namespaces, for example:

 given().
                config(newConfig().xmlConfig(xmlConfig().with().namespaceAware(true))).
 expect().
                body(hasXPath("/db:package-database", namespaceContext)).
when().
                get("/package-db-xml");

I'm going to continue working on namespace support for GPath expressions next.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 21, 2013 04:04:24_

I've now also added support for expecting on namespace aware XML, for example given the resource "/namespace-examplet" returns:

\<foo xmlns:ns="http://localhost/
         \<bar>sudo \</bar>
         \<ns:bar>make me a sandwich!</ns:bar>
      \</foo>

you can verify it like this:
 
     given().
              config(newConfig().xmlConfig(xmlConfig().declaredNamespace("ns", "http://localhost/")
      expect().
              body("bar.text()", equalTo("sudo make me a sandwich!")).
              body(":bar.text()", equalTo("sudo ")).
              body("ns:bar.text()", equalTo("make me a sandwich!")).
      when().
              get("/namespace-example");

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 21, 2013 04:04:50_

**Status:** Fixed

**Comment by testingtetser** [comment]
Hey all,

I have a api like this 
<root xmlns = "http://localhost.com">
<d1>testing1</d1>
<d2>testing2</d2>
<root>

I need to post this api with namespace-
httpRequest.body(reqxml).config(RestAssuredConfig.newConfig().xmlConfig(XmlConfig.xmlConfig().declareNamespace("ns1", "http://localhost.com")));

api is not including namespace while posting.I need some help.

Thank you.
