### ISSUE TITLE
Accept-Encoding request header cannot be changed

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#308]
_From [rus...@gmail.com](https://code.google.com/u/100491685150359683480/) on February 02, 2012 02:21:18_

What steps will reproduce the problem? 1. Set given().header("Accept-Encoding", "junk")... and see debug

What is the expected output?

Accept-Encoding: junk[EOL]

What do you see instead?

Accept-Encoding: gzip,deflate[EOL] What version of the product are you using? On what operating system? 1.4 (sorry, couldn't test with 1.5) on OSX Please provide any additional information below. It seems that RESTAssured always sends following header and it's impossible to override it:

	Accept-Encoding: gzip,deflate[EOL]

For example, following test will fail for webapp which provides uncompressed output when there's no Accept-Encoding header or Accept-Encoding does not contain "deflate" compression:

given().
	header("Accept-Encoding", "none").  // put junk into header, app looks for "deflate"
	pathParam("messageId", messageId).
expect().
	statusCode(200).and().
	header("Content-Type", equalTo("text/plain")).
	header("Content-Encoding", not(equalTo("deflate"))).  // we still get compressesed output!
when().
	get(REST_PATH);

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=154_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 01, 2012 23:16:13_

That's probably because that HTTP Builder doesn't care about it. In the next version I've forked HTTP Builder so now I can control most things. Not sure if this will make it to the next release though. Thanks for reporting.

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 03, 2012 01:46:27_

**Labels:** -Priority-Medium Priority-High 1.7

**Comment by johanhaleby** [comment]
_From [thomas.l...@gmail.com](https://code.google.com/u/101913723938941785364/) on June 26, 2013 08:42:23_

Any update or workaround for this issue?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on June 26, 2013 22:38:46_

No not yet :(

**Comment by johanhaleby** [comment]
_From [thomas.l...@gmail.com](https://code.google.com/u/101913723938941785364/) on June 28, 2013 05:07:26_

In RequestSpecificationImpl.grooy, RestAssuredHttpBuilder.doRequest(): headers are added but not overriden. The problem is that the "Accept-Encoding" header has already been set in the constructor of the ancestor class HTTPBuilder:

this.setContentEncoding(ContentEncoding.Type.GZIP,ContentEncoding.Type.DEFLATE)

Maybe a quick & dirty fix would be to delete this line (why would the HTTP client enable compression if not asked by the API user anyway ?).

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 01, 2013 03:46:16_

The problem with the quick fix is that it breaks backward compatibility without a good way to add GZIP support. I think we need to solve it in a better way.

**Comment by johanhaleby** [comment]
_From [thomas.l...@gmail.com](https://code.google.com/u/101913723938941785364/) on July 01, 2013 04:59:38_

That's why I called it dirty :-)
Another simple way would be to allow overriding headers. Is there a reason to only allow adding headers but not override already existing ones ?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 01, 2013 05:19:00_

The only reason is that Rest Assured forked HTTP Builder which had this as default behavior. I've simply not have time to fix it properly :)

**Comment by johanhaleby** [comment]
_From [thomas.l...@gmail.com](https://code.google.com/u/101913723938941785364/) on July 02, 2013 06:18:29_

I propose a pull request that keeps the default behavior. Tell me what you think about it: https://github.com/jayway/rest-assured/pull/17

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 02, 2013 22:26:39_

Good work! However I would prefer to have it in a configuration, called something like ContentEncodingConfig or AcceptEncodingConfig. This way it's possible to define it statically for all requests (using RestAssured.config = ..) or using it an a request specification builder for better re-use. See for example com.jayway.restassured.conf ig.ObjectMapperConfig. It might be a good idea to a have a shortcut to setting the content encoders like you've done with the "acceptEncoding" method in the RequestSpecification as well. 

Btw, do you think it ought to be called "acceptEncoding" or "contentEncoding"/"contentEncoders"? Perhaps setting the Accept-Encoding header is just a side-effect of specifying a content encoder? 

So would you be so kind to make it a config instead and amend that to the pull request? I think you've done a great start but making it a config would, in my view, be a more correct way to do it for the reasons mentioned earlier.

**Comment by johanhaleby** [comment]
_From [thomas.l...@gmail.com](https://code.google.com/u/101913723938941785364/) on July 03, 2013 07:36:11_

I tried to follow your advices in my new commit.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 03, 2013 22:56:14_

Thanks! I'll try to take a look at it during the day or this evening.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 14, 2013 01:12:49_

You can now configure this in the DecoderConfig

**Status:** Fixed

**Comment by dilanik** [comment]
@johanhaleby can you please guide with an example on how we configure this in DecoderConfig ?
