### ISSUE TITLE
Binary body() content method ignores given contentType specification

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#321]
_From [kmin...@gmail.com](https://code.google.com/u/107309578465571932208/) on April 23, 2012 20:09:10_

What steps will reproduce the problem? The code below...

byte[] bytes = "<tag attr='value'>/".getBytes( "UTF-8" );
given().contentType("application/xml").body(bytes).when().post("http://localhost:9999/test");

produces this HTTP request.  Note there is no Content-Type header even though it was specified.

POST /test HTTP/1.1
Accept: */*
Content-Length: 19
Host: localhost:9999
Connection: Keep-Alive
Accept-Encoding: gzip,deflate

\<tag attr='value'> What is the expected output? What do you see instead? POST /test HTTP/1.1
Accept: */*
Content-Length: 19
Content-Type: application/xml
Host: localhost:9999
Connection: Keep-Alive
Accept-Encoding: gzip,deflate

\<tag attr='value'> What version of the product are you using? On what operating system? Restlet: 1.6.1
MaxOS: 10.7.3 Please provide any additional information below. The code below produces the expected HTTP request...

given().header(new Header("Content-Type","application/xml")).body(bytes).when().post("http://localhost:9999/test");

Note also that I basically need to do this because there isn't currently a way to specify a custom ObjectMapper but that is addressed in other existing issues.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=167_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on April 26, 2012 00:54:26_

Hi, 

This was indeed a quite serious bug! I've fixed it in trunk now and you can see if it works for you if you depend on 1.6.2-SNAPSHOT after having added the snapshot repo:

\<repositories>
        \<repository>
            \<id>sonatype</id>
            \<url> https://oss.sonatype.org/content/repositories/snapshots/</url> \<snapshots />
        \</repository>
\</repositories>

Also bare in mind that if you want to make sure that your request body is indeed going to use UTF-8 you need to supply the charset to the content-type header OR configure it as the default request content charset using the detailed configuration in REST Assured (search for it on the usage page).

**Status:** Fixed  
  **Labels:** -Priority-Medium Priority-High

**Comment by johanhaleby** [comment]
_From [kmin...@gmail.com](https://code.google.com/u/107309578465571932208/) on April 26, 2012 07:51:42_

Hi,
Thank you very much for the quick turn around!  I've verified that 1.6.2-SNAPSHOT does resolve the issue.  For future readers the charset point is an important one.  To that end, I've verified that this mechanism can be used to control that...  

given().contentType("text/plain; charset=UTF-8").body( "TEST".getBytes( "UTF-8" ) ).when().post( "http://localhost:8888/test );

This produces the expected HTTP request...

POST /test HTTP/1.1
Accept: */*
Content-Length: 4
Content-Type: text/plain; charset=UTF-8
Host: localhost:8888
Connection: Keep-Alive
Accept-Encoding: gzip,deflate

TEST

**Comment by hansenmc** [comment]
+1 Encountered a similar issue performing PUT for binary content using RestAssured v2.3.1 on Windows. The bytes were mangled in the receiving system, and I could not figure out why. Appending " charset=UTF-8" to the contentType value resolved the issue!

**Comment by johanhaleby** [comment]
Try upgrading to 3.0.0 since 2.3.1 is very old

**Comment by hansenmc** [comment]
Will do. I'm working on a legacy system that obviously has older dependencies. Just wanted to mention the issue and version, so that it's searchable in Google to help anyone else that might be having similar issues.

**Comment by johanhaleby** [comment]
Have you had a chance to try it with 3.0.0?

**Comment by hansenmc** [comment]
@johanhaleby yes, I ran the same code with v3.0.0 and did not have an issue. Nothing to worry about with the current release. Simply updating to the latest would resolve the issue without hacking in a solution to code around the issue.

**Comment by johanhaleby** [comment]
Ok, glad to hear it. Thanks for getting back.
