### ISSUE TITLE
Support additional transports

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#365]
_From [torr0...@gmail.com](https://code.google.com/u/113194881606004254092/) on December 14, 2012 18:54:33_

This library is pretty cool. I only wish it was usable in unit tests that take advantage of vm transports. For example, CXF allows rest services to be exposed over a local transport.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=211_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 17, 2012 03:30:32_

What do you mean by other transports? Do you mean for example VM pipes etc?

**Comment by johanhaleby** [comment]
_From [torr0...@gmail.com](https://code.google.com/u/113194881606004254092/) on December 17, 2012 06:46:32_

I mean providing a means to handle different transport protocols vs the message contents. I specifically referenced CXF which has a pluggable transport system ( http://cxf.apache.org/docs/custom-transport.html ). One of which is a local VM transport that aids testing without having to spin up an HTTP server. Many/most ESBs also provide various protocols for moving messages around.

The crux of this issue, IMHO, is that rest-assured relies on Apache's HTTP components. Correct me if I'm wrong, I didn't do a deep dive on the code. Therefore, it is tied to HTTP. Abstracting this bit might expand the use cases that rest-assured could be applied to. The rest-assured DSL is terrifically readable. It would be great to be able to handle multiple protocols using it.

It is certainly true that HTTP over TCP/IP is almost always the protocol for rest messages. ESBs, CXF, as well as other frameworks provide message agnostic, pluggable, protocols for rest messages to travel over. While I do not assume that it is the responsibility of the rest-assured project to implement a CXF-local transport specific implementation, it would be phenomenal to abstract the transport details so that others (myself included) could provide means to connect to VM, JMS, etc. endpoints using REST messages.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 17, 2012 07:09:21_

While this is a good idea it'll require a massive rewrite and I can't see myself finding the time needed to do so in a foreseeable future. If you want to help out with this please feel free to do so and I'll assist you in anyway I can. REST Assured was designed for HTTP only (which IS misleading I know).

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 22, 2014 02:00:48_

**Status:** WontFix

**Comment by sirrapa** [comment]
Hi,

Is there a workarround? I also like to use the local scheme to test my endpoints with RestAssured.

**Comment by johanhaleby** [comment]
What do you mean by local scheme?

**Comment by sirrapa** [comment]
I want to use the scheme local instead of http. (local:///service/endpoint)
I've got it working up until when com.jayway.restassured.internal.RequestSpecificationImpl determine the request is not localhost (hasAuthorityEqualToLocalhost(uri)) and adds the port number, which messes up de uri.

If this could be changed or somehow be configurable, i think it would work.

**Comment by johanhaleby** [comment]
Is this supported by Apache HTTP Client?

**Comment by sirrapa** [comment]
I'll try it and let you know

**Comment by johanhaleby** [comment]
Thanks.
