### ISSUE TITLE
support for multipart/mixed

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#374]
_From [bwalli...@gmail.com](https://code.google.com/u/118396933656001965097/) on March 04, 2013 01:25:31_

Setting the content type to multi-part/mixed and inserting multiParts() fails to output the body of the request. See forum https://groups.google.com/forum/#!topic/rest-assured/nzgFK8bKwqk Summary:

expect().statusCode(200).given().contentType("multipart/mixed").multiPart("metadata", "file", mapper.writeValueAsBytes(doc2), "application/json").multiPart("filedata", "HelloWorld.txt", bis2, "text/plain").when().put("/documentstore-service/IHE:919191/sections/testSection1");

doc2 is an object that can be JSON serialised and bis2 is an inputstream with a small amount of text available to the reader.

If I leave the contentType() out then it PUTs the whole body of the request with a type of multipart/form-data but when I put the content type in it looses the body of the request.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=220_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 19, 2013 10:47:16_

Perhaps you could try using the com.jayway.restassured.builder.MultiPartSpecBuilder and see if that works

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on June 04, 2014 06:38:21_

Closing because of no response from the issuer

**Status:** WontFix

**Comment by johanhaleby** [comment]
_From [ric.kla...@gmail.com](https://code.google.com/u/105863720207366232556/) on April 17, 2015 01:57:31_

MultiPartSpecBuilder does not resolve the issue same type of error. I see only empty bodies on the wire.

Workaround build the body via http client classes:

ByteArrayOutputStream bos = new ByteArrayOutputStream();
File upload = new File("upload.txt");
final String boundary = "-8<--- my simple boundary -->8---";
HttpEntity data = MultipartEntityBuilder.create()
   .setBoundary(boundary)
   .addTextBody("metadata", "{ \"foo\": \"bar\" }", org.apache.http.entity.ContentType.APPLICATION_JSON)
   .addBinaryBody("file", upload, org.apache.http.entity.ContentType.create("application/zip"), upload.getName())
                .build();
data.writeTo(bos);
ValidatableResponse response = given()
  .contentType("multipart/mixed; boundary=\"" + boundary + "\"")
  .body(bos.toByteArray())
  .post("/my-multi-part-mixed")
..... etc

**Comment by RocketRaccoon** [comment]
I have a simillar issue. When I send request with ids batch I'm expecting to send body with several json's related to each id. Is there any way to prepare body without using `MultipartEntityBuilder`?
