### ISSUE TITLE
Response.getSessionId() doesn't work for form-auth

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#383]
_From [vkra...@gmail.com](https://code.google.com/u/112718581933173099221/) on April 24, 2013 09:21:56_

\> What steps will reproduce the problem?
@Test
public void ping() {
    Response resp = given()
       .auth()
       .form("emem58", "heslo58", FormAuthConfig.springSecurity())
        .get("/ping"); 
    assertNotNull(resp.getSessionId()); //this failed
}

\> What is the expected output? What do you see instead?
resp.getSessionId() should be not null.

\> What version of the product are you using?
1.8.0

\> On what operating system?
Windows

\> Please provide any additional information below.
Communication is this one :
request : POST /rest/j_spring_security_check
response: HTTP/1.1 302 Found
          Set-Cookie: JSESSIONID=E2895F6AFD5354549A5D1A0C087C971B; Path=/rest/; HttpOnly
request : GET /rest/ping
          Cookie: JSESSIONID=E2895F6AFD5354549A5D1A0C087C971B
response: HTTP/1.1 200 OK
          ^^^ without any cookies

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=229_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on April 26, 2013 04:16:56_

Thanks for reporting!

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [lgregory...@gmail.com](https://code.google.com/u/118392033065116189723/) on August 27, 2013 09:30:07_

Is there a workaround for this defect? I would love to have this resolved...we have a sessionid which changes after login, and I don't have a way to access the new sessionid for subsequent calls.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 27, 2013 22:44:46_

Not yet. I suspect that the sessionid is lost somewhere in the FormAuthFilter, probably on line 58. The session id (and possibly other headers) should be copied to the Response object. It would be cool if you could help out with this.

**Comment by johanhaleby** [comment]
_From [vkra...@gmail.com](https://code.google.com/u/112718581933173099221/) on August 27, 2013 23:12:24_

You do not know the code in detail, but the problem could be in the concept.
The second response doesn't contain 'Set-Cookie' header, so the session ID has to be remembered from the first response.

I've made an workaround, simplified code of it is attached.

Usage :
MySession ses = new MySession();
ses.login("username", "password")
ses.given()
   .with().pathParam(...)
   .expect().statusCode(HttpStatus.SC_OK)
   .when().get(...);
ses.given()...;

**Attachment:** [MySession.java](http://code.google.com/p/rest-assured/issues/detail?id=229#hc4)

**Comment by johanhaleby** [comment]
_From [vkra...@gmail.com](https://code.google.com/u/112718581933173099221/) on August 28, 2013 00:09:32_

\> You do not know the code in detail,
^^^^^ This should be : "I do not know"
My mistake, sorry.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 28, 2013 02:54:15_

No problem. Good that you found a work-around, I think it confirms my suspicions.  Thanks!

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 22, 2013 08:10:39_

I've now implemented better session support, you can now do:

SessionFilter sessionFilter = new SessionFilter();

      given().
              auth().form("John", "Doe").
              filter(sessionFilter).
      expect().
              statusCode(200).
      when().
              get("/formAuth");

      given().
              filter(sessionFilter). // Reuse sessionId from previous filter
      expect().
              statusCode(200).
      when().
              get("/formAuth");

String sessionId = sessionFilter.getSessionId();

Please try it out by depending on version 1.8.2-SNAPSHOT after having added the following repo:

\<repositories>
        \<repository>
            \<id>sonatype</id>
            \<url> https://oss.sonatype.org/content/repositories/snapshots/</url> \<snapshots />
        \</repository>
\</repositories>

**Status:** Fixed

**Comment by scaddenp** [comment]
Looks like identical code to what I have:
`        sessionFilter = new SessionFilter();
        given().
                auth().form("myuser","mypassword",FormAuthConfig.springSecurity()).
                filter(sessionFilter).
        when().
                get(baseUrl+"/login").
        then().
                statusCode(200);
        System.out.println("session id = " + sessionFilter.getSessionId());
        given().
                filter(sessionFilter).
        when().
                get(theApiBaseUrl+"/getAll").
        then().
                statusCode(200);
`
I get "session id = null" and then the second test fails with 403 instead of 200 as you would expect. I would assume a status 200 indicated successful authentication, but why no sessionid??

**Comment by scaddenp** [comment]
Looks to have a fetched a jsessionid. But is it from the request or the response to the login form?

**Comment by scaddenp** [comment]
Gee, it is all in how you hold your tongue. I changed to explicit FormAuthConfig and now it works. Phew.
