### ISSUE TITLE
Custom cookie parsing fails when request contains redirect

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#389]
_From [everf...@gmail.com](https://code.google.com/u/100456722887713625293/) on May 11, 2013 20:15:23_

Given: A request with a redirect as a result, f.e.

@Test
    public void logAll()
    {
        RestAssured.reset();
        
        given().log().all().when().get("/demo"); //setting cookies, HTTP 302
    }

expected: request can be used like all others.
actual result:

Request method:	GET
Request path:	http://localhost:8080/demo
Request params:	\<none>
Query params:	\<none>
Form params:	\<none>
Path params:	\<none>
Headers:		Content-Type=*/*
Cookies:		\<none>
Body:			\<none>

Assumption: Since the Apache httpclient internally handles the redirect, rest assured is not noticing what happens before the final result.
This leads to lost cookies and possibly other problems.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=235_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 14, 2013 00:02:44_

I don't see that you're setting any cookies in the request?! Or do you mean to log the response? Here you're only logging the request.

**Comment by johanhaleby** [comment]
_From [everf...@gmail.com](https://code.google.com/u/100456722887713625293/) on May 18, 2013 15:30:10_

The response is containing Set-Cookie header and HTTP status 302 (redirect-after-post pattern)
You can see that rest-assured does not log any cookies.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 21, 2013 02:31:35_

You're only logging the HTTP request, not the response. In order to log the HTTP response you should use:

expect().log().all().when().get("/demo");

**Comment by johanhaleby** [comment]
_From [everf...@gmail.com](https://code.google.com/u/100456722887713625293/) on May 21, 2013 04:02:26_

Right, changed test case - still cookies not logged.

I even added a request logging filter like

final String body = given().filter(new RequestLoggingFilter()).expect().log().all().get("/demo").asString();

Request method:	GET
Request path:	.../demo
Request params:	\<none>
Query params:	\<none>
Form params:	\<none>
Path params:	\<none>
Headers:		Accept=application/json
				Content-Type=application/json
Cookies:		\<none>
Body:			\<none>

HTTP/1.1 404 Not Found //this is fine and expected
Date=Tue, 21 May 2013 11:00:17 GMT
Server=Apache
Strict-Transport-Security=max-age=2592000; includeSubDomains
X-Content-Type-Options=nosniff
X-XSS-Protection=1; mode=block
Vary=Accept-Encoding
Content-Encoding=gzip
Content-Length=182
Keep-Alive=timeout=5, max=100
Connection=Keep-Alive
Content-Type=text/html; charset=iso-8859-1

\<html xmlns=" http://www.w3.org/1999/xhtml ">


What I see is the *second* request beeing logged, not the first where the authentication happens/cookies are beeing set and a HTTP 302 is returned.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 21, 2013 04:10:55_

I don't understand, I don't see that you do any authentication in your example!?

**Comment by johanhaleby** [comment]
_From [everf...@gmail.com](https://code.google.com/u/100456722887713625293/) on May 21, 2013 04:15:48_

Accessing the special URL ("/demo") is sufficient for authentication in my application.
That requests results in 
HTTP 302 + set-cookie

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 21, 2013 04:20:03_

What kind of authentication are you using?

**Comment by johanhaleby** [comment]
_From [everf...@gmail.com](https://code.google.com/u/100456722887713625293/) on May 21, 2013 04:24:31_

Accessing that URL is sufficient as authentication. A session is created for the user then.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 21, 2013 04:48:01_

What if you configure RA to not follow redirects, does that mean that you get a cooke?

**Comment by johanhaleby** [comment]
_From [everf...@gmail.com](https://code.google.com/u/100456722887713625293/) on May 21, 2013 10:22:35_

final String cookie = given().redirects().follow(false).filter(new RequestLoggingFilter()).expect().log().all().get("/demo").cookie("JSESSIONID");
logger.info("Cookie:" +cookie);

Still no session cookie, neither in request logging filter, nor in the result of .cookie();

Request method:	GET
Request path:	..../demo
Request params:	\<none>
Query params:	\<none>
Form params:	\<none>
Path params:	\<none>
Headers:		Content-Type=*/*
Cookies:		\<none>
Body:			\<none>
HTTP/1.1 302 Found
Date=Tue, 21 May 2013 17:17:47 GMT
Server=Apache-Coyote/1.1
Strict-Transport-Security=max-age=2592000; includeSubDomains
X-Content-Type-Options=nosniff
X-XSS-Protection=1; mode=block
X-Version=1.0.0.CI-SNAPSHOT-7e87603
Location=....
Content-Language=en-US
Content-Length=0
Keep-Alive=timeout=5, max=100
Connection=Keep-Alive
INFO  n.b.p.i.HttpRestIT:104 - Cookie:null

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 21, 2013 23:29:38_

Are you really sure that your server really provides a cookie?

**Comment by johanhaleby** [comment]
_From [everf...@gmail.com](https://code.google.com/u/100456722887713625293/) on May 22, 2013 02:41:30_

Yes.

This is the workaround I have in place for RA-229, RA-234, RA-235 now. It is called in a @BeforeClass part of the junit test.

private static void authenticateQuirk() throws Exception
    {
        final CookieStore cookieStore = new BasicCookieStore();
        final HttpClient httpclient = HttpClientBuilder.create().setDefaultCookieStore(cookieStore).build();
        httpclient.execute(new HttpGet("/demo"));
        
        final List<Cookie> cookies = cookieStore.getCookies();
        
        for (final Cookie cookie : cookies)
        {
            if(cookie.getName().equals("JSESSIONID"))
            {
                final String sessionId = cookie.getValue();
                //RestAssured.sessionId = sessionId; // 234
                final com.jayway.restassured.response.Cookie sessionCookie = new com.jayway.restassured.response.Cookie.Builder("JSESSIONID", sessionId).build();
                RestAssured.requestSpecification.cookie(sessionCookie);
            }
        }
    }

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 22, 2013 02:51:39_

So if I were to reproduce this I could just create a resource that returns a cookie and a redirect at the same time? In these cases RA doesn't include the cookie?

**Comment by johanhaleby** [comment]
_From [everf...@gmail.com](https://code.google.com/u/100456722887713625293/) on May 22, 2013 02:57:05_

That is my current understanding of the issue.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 22, 2013 03:01:46_

Ok I'll try to see if I get reproduce it when I find some time. Thank you so far!

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 21, 2013 23:53:54_

I've tried to reproduce this but I can't. Here's my server resource: 

get("/redirect-and-set-cookie") {
    val url: String = {params("url")}
    val cookie: Cookie = new Cookie("cookieName", "cookieValue")
    response.addCookie(cookie)
    redirect(url)
  }

And this is the test:

        given().
                redirects().follow(false).
                param("url", "/hello").
        expect().
                statusCode(302).
                cookie("cookieName", "cookieValue").
                header("location", "http://localhost:8080/hello"
        when().
                get("/redirect-and-set-cookie");

This means that I get cookies when redirects are disabled. By default Rest Assured is configured not to include cookies in redirects but if you change that it'll be included on redirects as well:

        given().
                config(newConfig().httpClient(httpClientConfig().setParam(COOKIE_POLICY, BROWSER_COMPATIBILITY))).
                param("url", "/reflect").
        expect().
                statusCode(200).
                cookie("cookieName", "cookieValue").
        when().
                get("/redirect-and-set-cookie");

**Status:** Invalid

**Comment by RomCruz** [comment]
I was actually having the same issue wherein I thought RestAssured was not returning all the response headers particularly the SET-COOKIEs. In my case I realised that I was hitting the HTTP endpoint instead of HTTPS. When I changed the baseURI to have HTTPS, I got the SET-COOKIE headers (therefore the cookies themselves). Posting this here in case someone might find it useful and save a couple of hours :)

**Comment by johanhaleby** [comment]
@RomCruz Thanks for your comments

**Comment by draganstanisavljevic** [comment]
Hi John,

I have same issue. I read your last answer how to change default settings and pass cookie throw redirect, but I do not understand what value I should set for COOKIE_POLICY and BROWSER_COMPATIBILITY. Could you help, please?

**Comment by draganstanisavljevic** [comment]
I tried this, but does not work:
`given()
            .config(new RestAssuredConfig().httpClient(HttpClientConfig.httpClientConfig().setParam(ClientPNames.COOKIE_POLICY, CookiePolicy.BROWSER_COMPATIBILITY)))
            .when().redirects().follow(true).get("www.example.com");`

**Comment by qait-tarundwivedi** [comment]
+1
