### ISSUE TITLE
rest assured looses cookies are between requests

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#390]
_From [everf...@gmail.com](https://code.google.com/u/100456722887713625293/) on May 11, 2013 20:25:51_

I am using rest assured for multiple requests. It looks like cookies are lost, even when the underlying httpclient is configured to accept cookies.
Is a new instance created for each request? (If so, that should really be configurable)

@Test
    public void shouldKeepCookies()
    {
        RestAssured.reset();
        RestAssured.config = RestAssuredConfig.config().httpClient( new HttpClientConfig().setParam(ClientPNames.COOKIE_POLICY, CookiePolicy.BEST_MATCH));
        
        given().expect().statusCode(200).when().get("fancyInit"); //cookies are set here
        given().body("{}").expect().statusCode(200).when().post("process"); //no cookies are sent here
    }

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=236_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 13, 2013 23:57:38_

Yes a new client is created for each request. It would be nice to make this configurable. Please help out!

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 12, 2013 23:06:38_

The underlying http client is reinstantiated for each request. But it's now possible to configure this by providing your own http client factory, for example:

 given().
                config(newConfig().httpClient(HttpClientConfig.httpClientConfig().httpClientFactory(new HttpClientConfig.HttpClientFactory() {

                    @Override
                    public AbstractHttpClient createHttpClient() throws Exception {
                        return new SystemDefaultHttpClient();
                    }
                }))).

Instead of returning a new "SystemDefaultHttpClient" you can make sure that the same instance is reused. Please try this out by depending on version 1.8.2-SNAPSHOT after having added the following maven repo:

\<repositories>
        \<repository>
            \<id>sonatype</id>
            \<url> https://oss.sonatype.org/content/repositories/snapshots/</url> \<snapshots />
        \</repository>
\</repositories>

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 19, 2013 10:42:12_

**Status:** Fixed

**Comment by kvarela** [comment]
Thanks, so what is now the best way to reuse cookies between requests?

**Comment by johanhaleby** [comment]
Try the "CookieFilter"

**Comment by kvarela** [comment]
Awesome, worked like a charm. Thanks Johan!

**Comment by johanhaleby** [comment]
Glad you got it working

**Comment by dineshgd** [comment]
I want to avoid the cookies being reused for some testing purpose how can i do that?
Any suggestions would be great.

**Comment by johanhaleby** [comment]
Yes, use the CookieFilter
<http://static.javadoc.io/io.rest-assured/rest-assured/3.3.0/io/restassured/filter/cookie/CookieFilter.html>
.

**Comment by ravenblackdusk** [comment]
@johanhaleby CookieFilter isn't the perfect solution, as it only considers the first request and the last response; whereas there may be many redirections in between(in my example oauth login won't work because of this).
I've tried to configure the http client, but the cookie store remains empty:
```
def store = new BasicCookieStore()
RestAssured.config = newConfig().httpClient(
        httpClientConfig().reuseHttpClientInstance().httpClientFactory(
                new HttpClientConfig.HttpClientFactory() {
                    @Override
                    HttpClient createHttpClient() {
                        //noinspection GrDeprecatedAPIUsage: rest-assured needs to fix this first
                        new DefaultHttpClient().with(true) {
                            redirectStrategy = FOLLOW_POST_REDIRECT_STRATEGY
                            cookieStore = store
                        } as HttpClient
                    }
                }
        )
)
```
Perhaps when the cast to `AbstractHttpClient` is fixed http client creation like this would work:
```
HttpClients.custom().setRedirectStrategy(FOLLOW_POST_REDIRECT_STRATEGY)
        .setDefaultCookieStore(cookieStore).build()
```
As it works for me with spring's `RestTemplate`.
