### ISSUE TITLE
rest-assured fails with session handling when server sends multiple Set-Cookie: PHPSESSID ...

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#411]
_From [da...@blockhausmedien.at](https://code.google.com/u/104847855687661377547/) on September 24, 2013 22:08:20_

What steps will reproduce the problem? 1. Make a request to a server that creates multiple sessions at one request.
2. Receive multiple Set-Cookie headers containing different PHPSESSID (or other session cookies)
3. Extract the cookie and use it in the next request. What is the expected output? What do you see instead? According to the HTTP specification a server is allowed to send multiple cookies with the same name in one HTTP response. The client has to store only the last cookie found (e.g. here the sequential last PHPSESSID cookie header). 

rest-assured will only return the FIRST received PHPSESSID thus not complying with the HTTP specification and not allowing session handling in some circumstances (our server sadly generates two PHPSESSIDs with one session initiation). Please provide any additional information below. There should be the possibility to receive all Set-Cookie: PHPSESSID headers (not only the first received one) - or rest-assured should stick to the HTTP specification and dismiss an header if it is overwritten by a following one.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=257_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 24, 2013 22:18:09_

Thanks for the report, I was not aware of the fact that the client ought to return the last one. 

How ever it's possible to get all cookies if you like, just do e.g. "Cookies cookies = get("/resource").detailedCookies();". From this "cookies" object you should be able to get all cookies.

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 01, 2013 23:05:36_

This has now been fixed in master, please verify it if you like by depending on version 1.8.2-SNAPSHOT after having added the following repo:

\<repositories>
        \<repository>
            \<id>sonatype</id>
            \<url> https://oss.sonatype.org/content/repositories/snapshots/</url> \<snapshots />
        \</repository>
\</repositories>

**Status:** Fixed

**Comment by anmoldeep0123** [comment]
@johanhaleby  , thanks for your response , detailedCookies() helped me solve my problem of multiple Set-Cookie headers .
