### ISSUE TITLE
JSON Parser not able to parse numbers into double or float

### ISSUE THREAD

**Issue by ssuerbier** [jayway/rest-assured#460]
**What steps will reproduce the problem?**
1. HTTP service returns body {"number": 0.0}
2. trying to match this with then().body("number", Matchers.closeTo(0.0, 0.001))

**What is the expected output? What do you see instead?**
Expect the match to succeed, fails instead with error message
```
java.lang.AssertionError: JSON path number doesn't match.
Expected: a numeric value within <0.001> of <0.0>
  Actual: 0.0
```
**What version of the product are you using? On what operating system?**
OS: Mac OS X 10.10.4, Product Version: 2.4.1 from maven repository

I have a MWE but I do not know how to attach files here, also reported at https://code.google.com/p/rest-assured/issues/detail?id=416 with attachment.

**Comment by johanhaleby** [comment]
0.0 is a float in REST Assured and "closeTo" assumes a double value so that's probably why it doesn't work. You would have to use a different Hamcrest matcher (or write your own) that takes a float instead of a double.

**Comment by xinlmain** [comment]
Bumped into the same issue. Had to write my own matcher. Extend ```TypeSafeMatcher<Float>```
