### ISSUE TITLE
Support measuring time 

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#493]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on June 13, 2014 17:54:21_

Monitor time for a request just before it's sent to the server and when it's received by the client. For example:

long time = get("/x").timeInMs()

and:

given()... then().responseTime(lessThan(200));

Note that called "timeInMs" or "responseTime" must consume the body of the response.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=338_

**Comment by zhong88** [comment]
it would be really useful to put this feature in because our developers are really interested in measuring the response time when running the rest assured test..

**Comment by johanhaleby** [comment]
Thanks for the feedback. However it's important to remember that the "response time" you measure is from the perspective of the client and not the server. The server will process the request faster and the client will account for latency etc.

**Comment by johanhaleby** [comment]
If you're in desperate need of this I think it would be able to create your own custom filter and start a StopWatch and measure the request time. You could then put the time in a custom response header and validate it afterwards.

**Comment by zhong88** [comment]
Thanks for your suggestion! We would try to set up a custom watch in the code to test it out.

**Comment by upgundecha** [comment]
Hi @johanhaleby I have a similar need to measure the response time. Could you please throw some light on how custom filter can be used in this cases. Is there any example how custom filter works?

**Comment by peidong-hu** [comment]
Me too, interested in this feature.

**Comment by johanhaleby** [comment]
I've now implemented support for this. Examples:

Extract response time in milliseconds:

```java
long timeInMs = get("/lotto").time()
```

or using a specific time unit:

```java
long timeInSeconds = get("/lotto").timeIn(SECONDS);
```

Validation (milliseconds):

```java
when().
        get("/lotto").
then().
        responseTime(lessThan(2000L));
```

or using a specific time unit:

```java
when().
        get("/lotto").
then().
        responseTime(lessThan(2L), SECONDS);
```

Please note that response time measurement should be performed when the JVM is hot! (i.e. running a response time measurement when only running a single test will yield erroneous results)

Please try it out by depending on version `2.7.1-SNAPSHOT` after having added the following Maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

I want to support MockMvc and the legacy syntax as well but I've created a separate [issue](https://github.com/jayway/rest-assured/issues/617) for that. 

<b>I'd like to hear what you think about this:</b>

Should the validation DSL use long and not int? I assume that in most cases you don't validate against a long value. For example instead of doing:

```java
when().
        get("/lotto").
then().
        responseTime(lessThan(2L), SECONDS);
```

you could do:

```java
when().
        get("/lotto").
then().
        responseTime(lessThan(2), SECONDS);
```

which (to me) both reads and looks better. But it is indeed misleading since the time measurement could require a long value (but it's very unlikely imho). What do you think?

**Comment by upgundecha** [comment]
Thanks @johanhaleby for this. I think having int value over long will be a better option.

**Comment by johanhaleby** [comment]
Thanks for your comment. I'm thinking of maybe using "Number" instead which means that you can pass in both Long and Integer (but unfortunately also float and double). Not sure if that's a good idea.
