### ISSUE TITLE
SunCertPathBuilderException thrown because given().trustStore() seems to be ignored 

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#502]
_From [mgawine...@gmail.com](https://code.google.com/u/118109395287397240301/) on August 19, 2014 08:15:20_

What steps will reproduce the problem? given().trustStore() doesn't work as expected.

When I do

  System.setProperty("javax.net.ssl.trustStore", "jssecacerts.jks");
  System.setProperty("javax.net.ssl.trustStorePassword", "changeit");
  given()
    .get("/oauth/authorize");

the test goes green. However, when I set truststore only per given request:

    KeyStore trustStore = KeyStore.getInstance(KeyStore.getDefaultType());
    trustStore.load(new FileInputStream(new File("jssecacerts.jks")), "changeit".toCharArray());
    given()
      .trustStore(trustStore)
      .get("/oauth/authorize");

I get exception

  javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)

Why is it returning this error? What version of the product are you using? On what operating system? RestAssured 2.3.2, JDK 1.8, OSX 10.9.4 Please provide any additional information below.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=347_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 29, 2014 04:32:36_

There's a test in SSLITest that looks like this:

@Test public void
allows_specifying_trust_store_in_dsl() throws Exception {
    InputStream keyStoreStream = Thread.currentThread().getContextClassLoader().getResourceAsStream("truststore_cloudamqp.jks");
    KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
    keyStore.load(keyStoreStream, "cloud1234".toCharArray());

    given().trustStore(keyStore).then().get(" https://bunny.cloudamqp.com/api/").then().statusCode(200); }

And it works. So I'm not sure what is wrong on your part. You can use the SslConfig to configure additional details if required.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 23, 2014 02:07:57_

Closing because no response

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 23, 2014 02:08:42_

**Status:** WontFix

**Comment by jagpreet08** [comment]
I am getting this error -javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.ssl.Alerts.getSSLException(Unknown Source).

Can you please help me to fix it?
