### ISSUE TITLE
Not able to upload an Image file using Mulitpart in Rest Assured

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#532]
_From [vaibhave...@gmail.com](https://code.google.com/u/109601717922371246521/) on December 06, 2014 20:08:07_

What steps will reproduce the problem? 1. Trying to upload a image(jpg) file using mulitPart option in Rest Assured 
2. given()
			.contentType("image/jpg")
			.accept("application/json")
			.auth().oauth2("accessToken",OAuthSignature.QUERY_STRING)
		        .multiPart(new File("C:/Snap0000.jpg"))
			.post("/objects/files")
			.getStatusCode();
3.What is the expected output? What do you see instead?

Expected Code is 200.  I am getting 400. "Unable to read image info Couldn't read magic numbers to guess format." What version of the product are you using? On what operating system? 2.4.0 on Win 7 64 bit Please provide any additional information below.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=377_

**Comment by johanhaleby** [comment]
_From [vaibhave...@gmail.com](https://code.google.com/u/109601717922371246521/) on December 09, 2014 02:20:37_

I was able to figure out the reason why I am facing this problem. When I mention the content type as "image/jpeg" or any content type as a matter of fact, REST Assured is adding the charset at the end of content type which is leading to this problem.

So what it actually sends in the header is :

Accept=application/json
Content-Type=image/jpeg; charset=ISO-8859-1

This extra string is causing the problem i am facing. Any suggestions as to how I can send just "image/jpeg" in content type without the charset thing.

An help would be appreciated.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 30, 2014 01:03:44_

You can disable it using the EncoderConfig: https://code.google.com/p/rest-assured/wiki/Usage#Encoder_Config I'm also thinking about not adding a charset by default since some people seem to have problems with it. Charset seems strange to add to a charset that is binary anyways so. I'll add an issue for it.

**Status:** WontFix

**Comment by hetal96** [comment]
I am having same issue.  Please let me know if some one has any idea.
