### ISSUE TITLE
Spring @Value annotatoin not recognized by the RestAssuredMockMvc

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#569]
_From [gerardo....@gmail.com](https://code.google.com/u/109122632968757805939/) on July 07, 2015 15:00:42_

What steps will reproduce the problem? 1. Add the two classes into your workspace
2. Execute SpringValueAnnotationNotRecognizedTest
3. You will see that the test SpringValueAnnotationNotRecognizedTest.testControllerMethodThatWontRecognizeTheSpringValueAnnotation will fail, because the Spring's @Value Annotation is not recognized.

**Attachment:** [SpringValueAnnotationNotRecognizedTest.java SpringValueAnnotationNotRecognizedController.java](http://code.google.com/p/rest-assured/issues/detail?id=414)

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=414_

**Comment by johanhaleby** [comment]
Does this work if you write the test in plain Spring MockMvc?

**Comment by Igor-Petrov** [comment]
Hello, Johan
I faced the same problem and did some investigation. It works with plain Spring MockMvc. 
It does not work with standalone setup because bean factory (DefaultListableBeanFactory) is not created and therefore BeanExpressionResolver is not accessible.
The above test can be slightly changed to run successfully: https://gist.github.com/Igor-Petrov/5d9d0f6d8d1a06062653

**Comment by johanhaleby** [comment]
Hmm REST Assured Mock Mvc simply delegates "standaloneSetup" to MockMvc so I don't think there should to be any difference to using standaloneSetup in MockMvc. Are you absolutely sure that it works when using standalone setup with MockMvc!?

**Comment by Igor-Petrov** [comment]
Hi, Johan
yes, You are right. It does not work when using standalone setup with MockMvc. Looks like spring-test issue.

**Comment by johanhaleby** [comment]
I doubt that it's an issue though. You probably need to register a MockMvcConfigurer or something similar to get it working. Thanks for checking, I'll close the issue.
