### ISSUE TITLE
Link in the documentation broken

### ISSUE THREAD

**Issue by naturalprogrammer** [jayway/rest-assured#573]
https://github.com/jayway/rest-assured/wiki/Usage#example-3---complex-parsing-and-validation points to the link below, which shows 404:

http://www.jayway.com/2011/10/09/simple-parsing-of-complex-json-and-xml-documents-in-java/

**Comment by johanhaleby** [comment]
Yes this is true. Unfortunately it was removed from the server when they migrated the blog posts to a new version of Wordpress. I'll e-mail them again and see if they can manage to get it working. 

Thanks!
