### ISSUE TITLE
ResponseParseException when request is successful, but content-type is not set

### ISSUE THREAD

**Issue by michaelrussell** [jayway/rest-assured#577]
rest-assured 2.1.0
I'm doing a POST as part of an authorization step in my api, the successful post sets an authHeader that I extract and use in subsequent requests.  There is no content in the body of response, and hence content-type header is not being set.
When I do this post, rest-assured throws a "ResponseParseException: OK."
Looking at the response in the exception I can see the POST was successful (200 OK status), and the authHeader is set as expected.
Work around, for me, is to catch the exception and extract the header from the exception.getResponse().getAllHeaders()

**Comment by johanhaleby** [comment]
Is this still an issue in version 2.4.1?

**Comment by michaelrussell** [comment]
Nope, all fixed.  Sorry about that.
Thanks!

**Comment by johanhaleby** [comment]
No problem, thanks for letting us know.
