### ISSUE TITLE
How to specify conditional JSON path

### ISSUE THREAD

**Issue by Mikuu** [jayway/rest-assured#578]
Hi,

I'm new to rest assured and found it really useful.
Now I got a question that how can I specify some conditional JSON path which needs to check some elements exist?

e.g.
{
 "lotto":{
   "lottoId":5,
   "winning-numbers":[2,45,34,23,7,5,3],
   "winners":[{
     "winnerId":23,
     "numbers":[2,45,34,23,3,5]
   },{
     "winnerId":54,
     "numbers":[52,3,12,11,18,22]
   }]
  }
 }

I need to check there is NO winnerId=50 in above Jason, which is the best way to achieve it?
I googled some questions and got something like:

assertThat(jsonPath.getBoolean("any { it.key == 'fund_code' }"), is(true)); 
assertThat(jsonPath.getBoolean("models.any { it.containsKey('number_of_clients') }"), is(true)); 
body("data.find {it.attribute == 'smile'}.code", equalTo("Cancelled"))

I feel this "it" instance could be very useful, but I can only find some pieces of its examples, is there any full documents or descriptions about the "it" usage?

Thank you.

Ariman

**Comment by johanhaleby** [comment]
Please use the mailing list for asking questions. I'll be glad to help you out there.
