### ISSUE TITLE
Max-Age < 1 are not supported in a response

### ISSUE THREAD

**Issue by lucamolteni** [jayway/rest-assured#580]
In Cookie.java if we have a max-age < 0 it throws an exception

        /**
         * Set the maximum age of the cookie, specified in seconds,
         * By default, <code>-1</code> indicating the cookie will persist
         * until browser shutdown.
         *
         * @return	 an integer specifying the maximum age of the
         *				cookie in seconds; if negative, means
         *				the cookie persists until browser shutdown
         */
        public Builder setMaxAge(int maxAge) {
            if(maxAge < 0) {
                throw new IllegalArgumentException("Max-Age cannot be less than 0");
            }
            this.maxAge = maxAge;
            return this;
        }

Both the specification and restassured comment support a maxAge < 0 though.

Is this wanted? Am I missing something? Otherwise I can make a pull request removing the check.

**Comment by johanhaleby** [comment]
Thanks for reporting. Something is not right that's for sure :) Either the javadoc is wrong or the code is wrong. I'm not sure if the cookie really will be persisted until "the browser shutdown". It would be great if you could investigate what's really happening (I'm short on time right now). If the cookie really is persisted as the javadoc says then I would of course appreciate a pull request.

**Comment by manoj163** [comment]
Any update on this? I cannot make rest assured test case working while setting max age -1 for expiring cookie during browser shutdown. response().discardCookie(cookie) also seems to fail from play framework as it sets max-age as -86400

**Comment by johanhaleby** [comment]
No not from my side :( Perhaps you could look into it and provide a pull request?

**Comment by dhirenmudgil** [comment]
Can somebody help me out. I am getting this exception when i create a token with sha1. Else without sha1 it is working fine.

I get the exception "Max-Age cannot be less than 0"
