### ISSUE TITLE
 java.net.ConnectException: Connection refused when setting baseUri as RequestSpecification

### ISSUE THREAD

**Issue by Potwor** [jayway/rest-assured#582]
I want to avoid using static fields, to avoid problems when running tests multi thread.
code:

private String baseUri;

@Before
public void setUp(){
baseUri = "some base uri";
}

@Test 
public void test1() {
given().baseUri(baseUri).param("param1", "value1").param("param2", "value2")
.when().get("some address")
.then().statusCode(200);
}

@Test 
public void test2() {
given(someHeader).baseUri(baseUri).param("param1", "value1").param("param2", "value2")
.when().get("some address")
.then().statusCode(200);
}

@Test 
public void test3() {
given(someHeader).baseUri(baseUri).spec(someSpecificationWithThisParameters)
.when().get("some address")
.then().statusCode(200);
}

@Test 
public void test4() {
given().baseUri(baseUri).spec(someSpecificationWithThisParameters)
.when().get("some address")
.then().statusCode(200);
}

All of these tests, except test1, throws java.net.ConnectException: Connection refused: connect.
It looks like RequestSpecification has some problems with not using static baseURI. 
I try also to set baseURI in RequestSpecification, but it fails too. 
I need to use RequestSpecification to make tests clear and easy to extend and fix.

**Comment by johanhaleby** [comment]
You can use a [request specification](https://github.com/jayway/rest-assured/wiki/Usage#specification-re-use). And please use the mailing list when asking questions in the future.

**Comment by Potwor** [comment]
I tried this too. Same exception was thrown.

2015-09-01 12:30 GMT+02:00 Johan Haleby <notifications@github.com>:

**Comment by g-tiwari** [comment]
I am also getting the same issue. recently in my code , I have started using RestAssured.BaseUri and it gives me exception - 
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)

**Comment by aali-khalid** [comment]
I'm seeing this too. Did anyone find a solution yet?

**Comment by aali-khalid** [comment]
Solved it.

By default the RequestSpecification object has the baseURI value is set as "LocalHost.." and the session ID is set as "SessionID" or something. Set both these parameters properly and it should work fine. In my case:

`       builder.setBaseUri("http://v303t7qa");
        builder.setSessionId("S31508252");`

builder being the RequestSpecification object

**Comment by Learner-max** [comment]
hey any solution to above issue

**Comment by hemil48** [comment]
did you find any solution @Learner-max ?

**Comment by BBmykola** [comment]
any solution?

**Comment by Mister1Burger** [comment]
I solved this problem by adding next annotation to my test class
`@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT, properties = ["server.port=8080"])`
