### ISSUE TITLE
Add support for other kinds of multipart requests

### ISSUE THREAD

**Issue by elnur** [jayway/rest-assured#585]
Currently, REST Assured supports only `multipart/form-data` for multipart requests. If I set it to, say, `multipart/related` or `multipart/mixed`, it doesn't set the boundary and doesn't populate the request body.

Given that `multipart/form-data` rarely if ever makes sense for RESTful APIs and REST Assured is focused on testing RESTful APIs, this is a serious deficiency that prevents me from testing my API properly.

For a good example of using other kinds of multipart requests, see [Google Drive API docs](https://developers.google.com/drive/web/manage-uploads).

**Comment by johanhaleby** [comment]
Thanks for reporting, I'll see what I can do. 

> If I set it to, say, multipart/related or multipart/mixed, it doesn't set the boundary and doesn't populate the request body.

How do you try to set it now? What would be a good way to set it (API wise)?

**Comment by elnur** [comment]
Basically, I'm currently stuck with using `multipart/form-data` in tests. It's simpler to do that instead of messing with boundaries and parts manually, even though now my tests don't reflect the real usage of the API. I don't really care what kind of multipart request comes to the API; all I care is that it's `multipart/*`. But the docs of the API will tell the clients to use either `multipart/mixed` or `multipart/related` — I haven't decided which one yet.

I guess the problem in REST Assured is caused by the [MULTIPART_FORM_DATA](https://github.com/jayway/rest-assured/blob/master/rest-assured/src/main/groovy/com/jayway/restassured/internal/RequestSpecificationImpl.groovy#L72) constant and assumption that that's the only kind of multipart requests.

Since all other [multipart subtypes](https://en.wikipedia.org/wiki/MIME#Multipart_subtypes) don't need any special handling beyond what you already do for `multipart/form-data`, it should be pretty simple to add support for `multipart/*` instead of checking exactly for `multipart/form-data`. As long as we can set `Content-Type` and other headers for each part, there's nothing else special to do in REST Assured.

**Comment by johanhaleby** [comment]
Just to make it clear, you're not interested in setting the `Content-Disposition` to something other than "form-data"? You're only interested in setting the `Content-Type` header to something different than "multipart/form-data"? Because if it's the first then I think it'll be harder (Apache Http Client doesn't even seem to support this afaict).

**Comment by johanhaleby** [comment]
I think I've solved this now. Please try it out by depending on version `2.5.1-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

I've also made it possible to configure default subtype using the `MultiPartConfig`. For example if you want to use "multipart/mixed" for all request you can do:

```java
RestAssured.config = RestAssured.config().multiPartConfig(multiPartConfig().defaultSubtype("mixed"));
```

And in all subsequent requests that specifies a multipart as content will have `content-type` equal to "multipart/mixed".

**Comment by johanhaleby** [comment]
I'm closing this issue for now. Please tell me if something is not working as expected an I'll reopen it.

**Comment by elnur** [comment]
Sorry for the late reply — been really busy.

> Just to make it clear, you're only interested in setting the Content-Type header to something different than "multipart/form-data"? Or are you also interested in setting the Content-Disposition to something other than "form-data"?

I'm not interested in `Content-Disposition` because it's used for email and I'm working on a RESTful API and it has nothing to do with email.

> I think I've solved this now. Please try it out by depending on version `2.5.1-SNAPSHOT`.

Just tried that and it worked with both `multipart/related` and `multipart/mixed`. At least, it worked when I ran a test via Gradle. For some reason, running the test via IDEA results into this:

```
java.lang.NoSuchMethodError: org.apache.http.entity.ContentType.withParameters([Lorg/apache/http/NameValuePair;)Lorg/apache/http/entity/ContentType;
	at org.apache.http.entity.mime.MultipartEntityBuilder.buildEntity(MultipartEntityBuilder.java:219)
...
```
This is the first time I'm seeing a difference between Gradle and IDEA's test runner. My guess is IDEA doesn't resolve dependencies properly. I'll wait for the `2.5.1` release and try again.

Anyway, you've done a great job and thank you for solving the problem so quickly. Much appreciated!

**Comment by johanhaleby** [comment]
Thanks for trying it out. 

I think there's something different in the way that IDEA and Gradle uses the classpath. That happens (unfortunately). Try moving REST Assured to the top of your dependencies.

`Content-Disposition` is not only used for e-mails, see [RFC](https://www.ietf.org/rfc/rfc2388.txt).
