### ISSUE TITLE
Multipart file control name is always the default control name for one of the multiPart() methods

### ISSUE THREAD

**Issue by mikaelnousiainen** [jayway/rest-assured#588]
One of the multiPart() methods in RequestSpecificationImpl always uses the default control name, although the control name is one of the parameters: see https://github.com/jayway/rest-assured/blob/master/rest-assured/src/main/groovy/com/jayway/restassured/internal/RequestSpecificationImpl.groovy#L914

I'm using release 2.5.0 (which is the latest one).

```groovy
  def RequestSpecification multiPart(String name, File file, String mimeType) {
    multiParts << new MultiPartInternal(controlName: restAssuredConfig().getMultiPartConfig().defaultControlName(), content: file, mimeType: mimeType, fileName: file.getName())
    this
  }
```

**Comment by johanhaleby** [comment]
Thanks, that's a mistake.

**Comment by johanhaleby** [comment]
Fixed in master
