### ISSUE TITLE
RestAssuredMockMvc miss effective way to set header accept()

### ISSUE THREAD

**Issue by jiechu** [jayway/rest-assured#591]
RestAssured.given() returns RequestSpecification which has accept(...) method. But RestAssuredMockMvc returns MockMvcRequestSpecification which does not have accept(...) method. This method is effective way to set accept header. Otherwise I have to set manually.

**Comment by johanhaleby** [comment]
Thanks for reporting.

**Comment by johanhaleby** [comment]
Fixed
