### ISSUE TITLE
GPath inconsistency in XmlPath with namespaces

### ISSUE THREAD

**Issue by eeichinger** [jayway/rest-assured#592]
Without XML namespaces the GPath needs to include the root object name but when using namespaces it must not.

Assuming the following XML without namespaces:

```xml
<licensesResponse>
  <license-active>true</license-active>
</licensesResponse>
```

the corresponding GPath needs to be written as

```java
...
  .then()
     .body("'licensesResponse.license-active'", equalTo("true"))
```

but if the xml is namespaced

```xml
<licensesResponse xmlns='http://example.com/licenses'>
   <license-active>true</license-active>
</licensesResponse>
```

the corresponding GPath needs to be written as

```java
        given().config(config()
            .xmlConfig(xmlConfig()
                .namespaceAware(true)
                .declareNamespace("licenses", "http://example.com/licenses"))
        )
...
        .then()
               .body("licenses:license-active", equalTo("true"))
        ;
```

this seems due to the call to 

```java
return (T) xmlAssertion.getResult(input, convertToJavaObject, !getXmlPathConfig().hasDeclaredNamespaces());
```

in method `com.jayway.restassured.path.xml.XmlPath#getFromPath`

I am wondering what the rational behind `rootEvaluation = !getXmlPathConfig().hasDeclaredNamespaces()` is?

**Comment by johanhaleby** [comment]
The rational is to be compatible with the way it works in vanilla Groovy. See for example [here](http://stackoverflow.com/questions/8669766/namespace-handling-in-groovys-xmlslurper). I also find this annoying and I don't know why it is like it is. As you mention REST Assured could "work-around" it but I decided that Groovy compatibility matter more. Perhaps it should be configurable though?

**Comment by eeichinger** [comment]
as far as I can see the difference is made inside XmlPath and isn't related to Groovy. Vanilla Groovy asfaik always evaluates starting from the given object.

In v2.5.0, XMLAssertion.groovy, line 59:

```groovy
            } else if (rootEvaluation) {
                evaluationString = key.substring(indexOfDot);
            } else {
                evaluationString = key.startsWith(".") ? key : "." + key;
            }
```

the rootEvaluation flag only controls whether to strip the first path element or not. In the end it always evaluates the path relative to the object:

Given the gpath `licensesResponse.license-active`, it will also end up being passed XmlAssertion.eval() as "restAssuredXmlRootObject.license-active"

So passing `!getXmlPathConfig().hasDeclaredNamespaces()` only controls whether the first path element is stripped or not. Which seems odd to me.

**Comment by johanhaleby** [comment]
Now that I look into to it again I actually think that you are absolutely right. This means I've made a HUGE misstake and misunderstood how the XmlSlurper behaved when using namespaces. It would certainly explain a lot though (which is good!). 

This will be a non-backward compatible change but it must be fixed! I can't believe that no one have filed an issue for this earlier! Thanks a ton for being persistent :) If you have a chance to submit a pull request I would be even happier :)

**Comment by eeichinger** [comment]
the easiest fix would be to always pass rootEvaluation=true - or drop this flag altogether you reckon?

**Comment by johanhaleby** [comment]
If it's not needed then I suggest that we drop it. I think that tests will catch if there's a problem.

**Comment by eeichinger** [comment]
I was thinking about a config flag for backwards compatibility until the next major release. Too much effort you think?

**Comment by johanhaleby** [comment]
Yes I think that we should just ignore backward compatibility and just document it thoroughly. I always add a "non-backward compatible" section in the release notes.

**Comment by eeichinger** [comment]
there you go

**Comment by johanhaleby** [comment]
Thanks a lot for helping out! Really really appreciate it.
