### ISSUE TITLE
Add "map" functionality to headers

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#594]
It's quite common that header values are actually numbers and not strings but it's not possible to easily convert the strings to numbers in REST Assured. One solution could be to introduce a "Function" interface that allows you to do mapping before validation. For example:

```java
... then().header("someheader", val -> Integer.parseInt(val), lessThan(200)). .. 
... then().header("someheader", Integer::parseInt, lessThan(200)). .. 
```

**Comment by Zilev** [comment]
Hi @johanhaleby , how can I apply header as content-type header is applied? I mean like this:
![screenshot-1](https://cloud.githubusercontent.com/assets/9355851/11104932/2e1bbf30-88a2-11e5-850a-343afc3e568f.png)

I've already try this:
```
     given()
                .headers("My-Key", "123456789")
        .when()
                .get("http:/myURL/user")
        .then()
                .log().body();
```
but is not working, would you help me please? thanks in advance :smile:
