### ISSUE TITLE
Add support to compare response body to a template

### ISSUE THREAD

**Issue by ivos** [jayway/rest-assured#595]
I want to have a JSON file with a template of the expected response, load the file contents to a string and then in Rest assured assert that it matches the response body.

This will let me verify the response body elegantly at once as a whole, instead of writing tedious assertions on each and every bit of data in there. The template JSON file will also give anyone clearer idea of what response is expected than a bunch of assertions in Java code will ever do.

This will require a mechanism to declare which data in the response are dynamic (e.g. generated DB sequence ids, current timestamps, etc.) and should be somehow excluded from the actual response, e.g. by being replaced with a constant string value.

I do have this working in my own sort-of REST test client. I just came across Rest assured and when considering ditching my proprietary test client in favor of Rest assured I identified this as feature gap.

I am willing to contribute a proposal on this functionality in Rest assured.
Would you guys be willing to accept a feature like this? Does it fit with your concepts? Or am I missing something obvious?

Thanks. Ivo

**Comment by johanhaleby** [comment]
I think that you should do something like this:

1. Use something like [hamcrest-json](https://github.com/hertzsprung/hamcrest-json). This would work out of the box with REST Assured (`...then().body(sameJSONAs(..))`)
1. Use [json schema validation](https://github.com/jayway/rest-assured/wiki/Usage#json-schema-validation) which is supported by adding an additional module to REST Assured

Does this help?

**Comment by ivos** [comment]
The sameJSONAs() really does help, thanks for pointing me to it. It verifies the response content in the case there are no dynamic data and the response template exactly equals the actual response.

It does not compare the values as strings in junit assertEquals though, so the reporting of errors is a bit unfortunate.

Moreover it does not support any mechanism to handle responses with dynamic data. Maybe an extension of the SameJSONAs matcher would be an appropriate way for me to go. Anyway, this effectively transfers my issue from Rest assured to the hamcrest-json project. Thanks again for your prompt help.

(As for validating the response conforms to schema, I don't see any added value given that I will match the actual content of the response to a template.)

**Comment by Cs4r** [comment]
I also came across this problem recently.  I see that this ticket is closed since long time ago. Did you find a solution @ivos ?

Cheers

**Comment by ivos** [comment]
I did. I created my own matcher and I use JsonPath to reset values that dynamically change with every request. Inspiration below.

    /**
     * Asserts that values are equal JSON Strings while applying a replacing function on the JSON model.
     *
     * @param expected expected JSON value
     * @param replacer replacing function
     */
    public static org.hamcrest.Matcher<String> jsonEqualTo(
            String expected, Function<DocumentContext, DocumentContext> replacer) {
        return new IsJsonEqual<>(expected, replacer);
    }

    public static class IsJsonEqual<T> extends BaseMatcher<String> {
        private final String expected;
        private final Function<DocumentContext, DocumentContext> replacer;

        public IsJsonEqual(String expected, Function<DocumentContext, DocumentContext> replacer) {
            this.expected = expected;
            this.replacer = replacer;
        }

        private String normalize(String content) {
            String json = JsonFormatter.format(content);
            // pre-format first to ensure pretty error reporting of invalid JSON
            if (null != replacer) {
                json = replacer.apply(JsonPath.parse(json)).jsonString();
                json = JsonFormatter.format(json); // re-format again after replacing
            }
            return json;
        }

        @Override
        public boolean matches(Object actual) {
            String expectedNormalized = normalize(expected);
            String actualNormalized = normalize((String) actual);
            boolean match = areEqual(expectedNormalized, actualNormalized);
            if (!match) {
                assertEquals(expectedNormalized, actualNormalized);
            }
            return match;
        }

        @Override
        public void describeTo(Description description) {
            description.appendValue(expected);
        }
    }

    public class JsonFormatter {
        /**
         * Re-format a JSON {@link String}.
         *
         * @param json JSON {@link String} to be formatted
         * @return Re-formatted JSON {@link String}
         */
        public static String format(String json) {
            return convertToString(convertToJson(json));
        }
    
        private static JsonNode convertToJson(String json) {
            ObjectMapper objectMapper = new ObjectMapper();
            try {
                return objectMapper.readTree(json);
            } catch (Exception e) {
                throw new RuntimeException(
                        "Cannot parse JSON string. Does it contain valid JSON? The content is:\n" + json, e);
            }
        }
    
        private static String convertToString(JsonNode jsonNode) {
            ObjectMapper objectMapper = new ObjectMapper();
            try {
                StringWriter stringWriter = new StringWriter();
                JsonGenerator generator = new JsonFactory().createGenerator(stringWriter);
                generator.useDefaultPrettyPrinter();
                objectMapper.writeTree(generator, jsonNode);
                return stringWriter.toString();
            } catch (Exception e) {
                throw new RuntimeException("Cannot format JSON string. Does it contain valid JSON?", e);
            }
        }
    }

And then you can:

    RestAssured...
        .then()
        .body(jsonEqualTo(expectedResponse, ctx -> ctx.set("$.id", 1)));

or just (can be overloaded to prevent that null):

    RestAssured...
        .then()
        .body(jsonEqualTo(expectedResponse, null));

Hope this helps. Cheers.

**Comment by dkb12** [comment]
@ivos : How would this can be applied, in below scenario:
1. I have expected json already saved at a place.
2. I have taken out a json object from rest assured response which is actual json.
Now, I want to compare all or certain fields from these two objects [irrespective of the json complexity]

Will your solution apply here? If Yes, how? Can you please modify it a suiting to this requirement or give me pointer suggestion on how to do it.

**Comment by ivos** [comment]
@dkb12 If the difference is your actual JSON data is not a String but a JsonNode, then either format it to String first and then use the solution above, or amend the solution to accept a JsonNode as well as a String (in which case the convertToJson method in JsonFormatter above can be skipped).
