### ISSUE TITLE
Nicer integration for proxy authenication

### ISSUE THREAD

**Issue by andrew-sumner** [jayway/rest-assured#597]
As per http://stackoverflow.com/questions/33006368/how-authenticate-a-rest-call-from-behind-a-corporate-proxy-using-rest-assured/33072951#33072951

While not exactly hard to work around, it would be nice to specify proxy authorization in a similar manner to the RestAssured auth() methods.  This is how I was able to authenticate against our proxy:

	PreemptiveBasicAuthScheme auth = new PreemptiveBasicAuthScheme();
	auth.setUserName("XXXX");
	auth.setPassword("XXXX");
	
	String url = "http://jsonplaceholder.typicode.com/posts";
		
	Response r2 = RestAssured
			.given()			
			.header("Proxy-Authorization", auth.generateAuthToken())			
			.proxy("corporate.proxy", 8080)
			.get(url);

**Comment by johanhaleby** [comment]
Thanks for the pull request. I'll try to make it better integrated in the next release. Would something like this be ok?

```java
Response r2 = RestAssured
        .given()            
        .header("Proxy-Authorization", auth.generateAuthToken())            
        .proxy("corporate.proxy", 8080, preemptive().basic("XXXX", "XXXX"))
        .get(url);
```

I'm not sure if it's possible to make it (more) fluent without breaking the API.

**Comment by andrew-sumner** [comment]
Won't need the header call any more, and happy for it to work the same as the other auth mechanism, but whatever is easiest will do just fine.

Response r2 = RestAssured
        .given()            
        .proxy("corporate.proxy", 8080)
        .proxyAuth().basic("XXXX", "XXXX")
        .get(url);

**Comment by johanhaleby** [comment]
Thanks for your feedback

**Comment by johanhaleby** [comment]
I have added support for this now but you need to use a ProxySpecification (`com.jayway.restassured.specification.ProxySpecification`). For example:

```java
given().proxy(host("corporate.proxy").withPort(8080).withAuth("XXXX", "XXXX")). ..
```

Please try it out by depending on version 2.6.1-SNAPSHOT after having added the following repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```
