### ISSUE TITLE
Problem with cyrillic while parsing JSON response body

### ISSUE THREAD

**Issue by vltsu** [jayway/rest-assured#599]
Hello! 

I am working on Russian project and while validating JSON response body encountering encoding problems:

The response body:
`
{
    "title" : "Информационные технологии, интернет, телеком"
}
`

But I get such error:

`JSON path title doesn't match.
Expected: is "Информационные технологии, интернет, телеком"
  Actual: Р?РЅС„РѕСЂРјР°С†РёРѕРЅРЅС‹Рµ С‚РµС…РЅРѕР»РѕРіРёРё, РёРЅС‚РµСЂРЅРµС‚, С‚РµР»РµРєРѕРј`

While looking for a root of problem I found this line:
https://github.com/jayway/rest-assured/blob/master/rest-assured/src/main/groovy/com/jayway/restassured/internal/ContentParser.groovy#L43

It should be:
`slurper.parse(new InputStreamReader(new BufferedInputStream(response.asInputStream()), StandardCharsets.UTF_8))`  or it should be an ability to set charset from config.

**Comment by johanhaleby** [comment]
REST Assured should use the charset specified in the content-type of the response. If no charset is specified you can configure a default charset for all content-types or per individual content-type. So you should be able to configure this using the DecoderConfig, see https://github.com/jayway/rest-assured/wiki/Usage#decoder-config. Does this help?

**Comment by vltsu** [comment]
Hello @johanhaleby! Thank you for the fast reply.
Yes, maybe it would be good approach to use decoderConfig().defaultContentCharset() to set charset while parsing inputStream. But now this configuration option not used here https://github.com/jayway/rest-assured/blob/master/rest-assured/src/main/groovy/com/jayway/restassured/internal/ContentParser.groovy#L43

**Comment by johanhaleby** [comment]
Ah you're right. Thanks for the investigation, I'll try to implement it.

**Comment by johanhaleby** [comment]
I've tried to implement this now. Please try it out by depending on version 2.6.1-SNAPSHOT after having added the following repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

I'll close the issue for now, please let me know if I should reopen it.

**Comment by vltsu** [comment]
@johanhaleby Thanks, it works like a charm)
