### ISSUE TITLE
Can't change baseURI and port in a filter

### ISSUE THREAD

**Issue by aistoica** [jayway/rest-assured#600]
Hello,

I have the following situation:

I construct a request using the following code:

1. the properties are set in rest-assured statically

RestAssured.port = Integer.parseInt(property.getProperty("appPort"));
RestAssured.baseURI = property.getProperty("appBaseURI");
RestAssured.basePath = property.getProperty("appBasePath");

2. the request is made as follows:

given().filter(new CustomRequestFilter())
       .contentType(ContentType.JSON)
       .body(json)
       .post("/groups");

3. The filter is:

public class CustomRequestFilter implements Filter{

public static Map<String, String> loginCookies;

@Override
public Response filter(FilterableRequestSpecification requestSpec, FilterableResponseSpecification responseSpec, FilterContext ctx) {
   
    if(loginCookies!= null){
        requestSpec.baseUri(httpsUri)
                   .port(443)
                   .cookies(loginCookies)
                   .redirects().follow(true)
                   .config(config().sslConfig(new SSLConfig().relaxedHTTPSValidation()));
    }
    return ctx.next(requestSpec, responseSpec);
}
}

Running the above scenario doesn't change the URI and port even if the loginCookies are not null. The cookies are put in the request and all the remaining config, like redirect and sslConfig.

It seems that this is a bug. There is also a group thread for this: https://groups.google.com/forum/#!topic/rest-assured/SfoNKxUx4Bo

**Comment by johanhaleby** [comment]
Thanks for reporting

**Comment by johanhaleby** [comment]
I think I've fixed this now. Please try it out by depending on version 2.6.1-SNAPSHOT after having added the following repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by aistoica** [comment]
It is fixed in the snapshot provided. When do you think the release will be available?

Thank you very much for the fix. It was an important part for our project. Cheers.

**Comment by johanhaleby** [comment]
Thanks for trying it out. I'll probably release a new version in 1-2 weeks (maybe sooner).
