### ISSUE TITLE
EncoderConfig uses >= JDK 7 class

### ISSUE THREAD

**Issue by ThorbenLindhauer** [jayway/rest-assured#602]
EncoderConfig uses the class java.nio.charset.StandardCharsets, see https://github.com/jayway/rest-assured/blob/master/rest-assured/src/main/java/com/jayway/restassured/config/EncoderConfig.java#L38. This class was introduced with JDK 7, so using it prevents using rest-assured with JDK 6.

Setting the constant to the String value "UTF-8" is probably fine since the UTF8 charset's name is unlikely to change in any future Java version.

Side note: There are also some tests making use of that class.

**Comment by johanhaleby** [comment]
Thanks for reporting, if you find something similar elsewhere that prevents REST Assured from being used in JDK 6 please let me know.

**Comment by johanhaleby** [comment]
I've fixed this now and I've created a new snapshot that you can use if you like (version 2.6.1-SNAPSHOT). If you want to try it out you need to add the following Maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by mpmoeller** [comment]
Hey @johanhaleby 

Might it be that this is also the case for DecoderConfig? See:

https://github.com/jayway/rest-assured/blob/master/rest-assured/src/main/java/com/jayway/restassured/config/DecoderConfig.java#L37

Best,
Martin

**Comment by johanhaleby** [comment]
@mpmoeller Thanks for pointing this out, I've now fixed it.

**Comment by mpmoeller** [comment]
Thanks so much & Happy Holidays!
