### ISSUE TITLE
Enable Spring Rest Docs

### ISSUE THREAD

**Issue by patricksan** [jayway/rest-assured#606]
## Issue
Create a way to supply an instance of _RestDocumentationRequestBuilders_ to the _rest-assured_. This would enable Spring Rest Docs in all scenarios. Today, it is not possible with _path parameters_

## Discussion
This was discussed with @johanhaleby. All details can be found on this post from Google Groups: https://groups.google.com/forum/#!topic/rest-assured/o5Wntwv4NB0

## Temporary solution
To fix this integration I hacked the code doing that:

```java
private static final String ATTRIBUTE_NAME_URL_TEMPLATE = "org.springframework.restdocs.urlTemplate";

@Test
public void testGetEnvironmentProjectInfoWasFound() {
    document.snippets(
            pathParameters(
                    parameterWithName("environmentName").description("The environmentName"),
                    parameterWithName("projectName").description("The projectName")
            ),
            responseFields(
                    fieldWithPath("projectVersionNumber").description("The Project version number"),
                    fieldWithPath("deploymentTime").description("deployment time")
            )
    );

    final String restUrl = "/environments/{environmentName}/projects/{projectName}";
    given()
            .attribute(ATTRIBUTE_NAME_URL_TEMPLATE, restUrl)
            .when()
            .get(restUrl, ENVIRONMENT_NAME, PROJECT_NAME)
            .then()
            .body("projectVersionNumber", is(PROJECT_VERSION_NUMBER))
            .body("deploymentTime", is(DateTimeFormat.forPattern("dd/MM/yyyy HH:mm").print(DEPLOYMENT_TIME)))
            .statusCode(HttpStatus.OK.value());
}
```

So here, I manually set an attribute  **_org.springframework.restdocs.urlTemplate_** with the value of my rest url. But the url is defined again in the **get()**.

## Solution
If I read the RestDocs API, we can find this:

> To make the path parameters available for documentation, the request must be built using one of the
> methods on RestDocumentationRequestBuilders rather than MockMvcRequestBuilders.

We could solve this, being able to supply an instance of _RestDocumentationRequestBuilders_ to the rest-assured.

@johanhaleby asked if it is already possible to supply an instance to the RestArruedMockMvc today, but I couldn't figure it out.

Another point we discussed was these:
> The ability of automatically choose RestDocumentationRequestBuilders rather than MockMvcRequestBuilders should not be the default implementation. 
> Maybe a method enableRestDocs() and in this scenario we look for the RestDocumentationRequestBuilders in the class path. It is interesting to give flexibility 
> but not everyone wants to use RestDocs.

Thanks!

**Comment by patricksan** [comment]
For your information: @greyfairer and @jurgenlust

**Comment by johanhaleby** [comment]
Thanks for reporting

**Comment by johanhaleby** [comment]
Where do you find `RestDocumentationRequestBuilders`? I've added spring restdocs 1.0.0 to the classpath but I can't seem to find a `RestDocumentationRequestBuilders`.

**Comment by patricksan** [comment]
``` java

package org.springframework.restdocs.mockmvc;

import java.net.URI;

import org.springframework.http.HttpMethod;
import org.springframework.restdocs.request.RequestDocumentation;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import org.springframework.test.web.servlet.request.MockMultipartHttpServletRequestBuilder;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;

/**
 * A drop-in replacement for {@link MockMvcRequestBuilders} that captures a request's URL
 * template and makes it available for documentation. Required when
 * {@link RequestDocumentation#pathParameters(org.springframework.restdocs.request.ParameterDescriptor...)
 * ) documenting path parameters} and recommended for general usage.
 * 
 * @author Andy Wilkinson
 * @see MockMvcRequestBuilders
 * @see RequestDocumentation#pathParameters(org.springframework.restdocs.request.ParameterDescriptor...)
 * @see RequestDocumentation#pathParameters(java.util.Map,
 * org.springframework.restdocs.request.ParameterDescriptor...)
 */
public abstract class RestDocumentationRequestBuilders {
}
```

More details: http://docs.spring.io/spring-restdocs/docs/1.0.0.RELEASE/api/org/springframework/restdocs/mockmvc/RestDocumentationRequestBuilders.html

**Comment by johanhaleby** [comment]
OK I only added the core module and not the mockmvc module. 

Anyways, is there a downside of adding the `org.springframework.restdocs.urlTemplate` request attribute automatically if restdocs mockmvc is in classpath? This could obviously be configurable as well. To me this seems like the only thing `RestDocumentationRequestBuilders` does?

**Comment by patricksan** [comment]
It would do the job. It is exactly what I’m doing today with my hack.
How would you configure that?

**Comment by johanhaleby** [comment]
Probably through a new config, RestDocsConfig or something similar (see [config](https://github.com/jayway/rest-assured/wiki/Usage#detailed-configuration) section if you don't know about config). There's already a [MockMvcConfig](https://github.com/jayway/rest-assured/blob/master/modules/spring-mock-mvc/src/main/java/com/jayway/restassured/module/mockmvc/config/MockMvcConfig.java) so I may just add it there since the Spring security stuff is already configurable from this config.

**Comment by patricksan** [comment]
Great!

**Comment by johanhaleby** [comment]
I've now added support for this but you still need to add `documentationConfiguration` manually. For example:

```java
@Rule
public final RestDocumentation restDocumentation = new RestDocumentation("target/generated-snippets");

given().
        standaloneSetup(new GreetingController(), documentationConfiguration(restDocumentation)).
        queryParam("name", "John").
when().
       get("/{path}", "greeting").
then().
        apply(document("greeting").snippets(
                pathParameters(
                        parameterWithName("path").description("The path to greeting")),
                responseFields(
                        fieldWithPath("id").description("The ID of the greeting"),
                        fieldWithPath("content").description("The content of the greeting"))
        )).
        body("id", equalTo(1)).
        body("content", equalTo("Hello, John!"));
```

I would have like to be able to remove the need for passing in the `documentationConfiguration` MockMvcConfigurer altogether but it seems too hard since it's coupled to a JUnit Rule. Please try it out by depending on version `2.6.1-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

Please reopen if there's anything not working as expected.

**Comment by patricksan** [comment]
@johanhaleby I just tested using version 2.7.0 and it is OK.
Thank you.
