### ISSUE TITLE
Perform a general action

### ISSUE THREAD

**Issue by patricksan** [jayway/rest-assured#607]
### Issue
With Spring Framework test I'm able to handle a _ResultHandler_. This is very interesting for post-actions.

### Simple Example
```java
 mockMvc.perform(get("/form")).andDo(print());
```

The method signature of andDo is:
``` java
	ResultActions andDo(ResultHandler handler) throws Exception;
```

### Solution
Would be great if we could have a way to execute this after _then()_, like:

``` java
given()
        .when()
        .get(/my-url)
        .then()
        .statusCode(HttpStatus.FOUND.value())
        .handle(print())
```

In this example, I called the method _handle()_ but it could be _andDo()_

### Where I want to use it
I would like to invoke a RestDocumentResultHandler like that:

``` java
.andDo(
                       document(
                               "get-project-version-from-environment", pathParameters(
                                       parameterWithName("environmentName").description("The environmentName"),
                                       parameterWithName("projectName").description("The projectName")
                               ),
                               responseFields(
                                       fieldWithPath("projectVersionNumber").description("The Project version number"),
                                       fieldWithPath("deploymentTime").description("deployment time")
                               )
                       )
               );
```

**Comment by johanhaleby** [comment]
You can already do this, but it's in the request specification:

`given().resultHandlers(..)`

But when I think about that might be a mistake... Perhaps they should be part of the response specification instead (i.e. after `then`).

**Comment by patricksan** [comment]
It is stranger to have a `resultHandlers` before the `then`. At this point is seems that the `result` is not ready yet because there is no response.

I would move it to the response specification.

**Comment by patricksan** [comment]
FYI: @greyfairer

**Comment by johanhaleby** [comment]
Should the method be called `resultHandlers` in the response specification or can/should we come up with a better name? For example:

```java
.. .then().perform(print())
```

or

```java
.. .then().with(print())
```

Any ideas?

**Comment by patricksan** [comment]
- `perform` I don't like because seems the same used for the `MockMvc` to start the mock.
- `with` is good. But seems more interesting for something before the `Result`, e.g: `get(xx).with(yy)`.

I would use `handle`

**Comment by johanhaleby** [comment]
Thanks for your input.

**Comment by johanhaleby** [comment]
I've opted to call the method `apply`. I feel that it's nicer than "handle" and more inline with "andDo" which is what it's called in MockMvc. For example:

```java
given().
        header(new Header("headerName", "John Doe")).
when().
        get("/header").
then().
        apply(print(), someOtherHandler).
        statusCode(200).
        body("headerName", equalTo("John Doe"));
```

Please tell me if you think this is a bad name. Please try it out by depending on version 2.6.1-SNAPSHOT after having added the following Maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by patricksan** [comment]
@johanhaleby I just tested using version 2.7.0 and it is OK.
Thank you.
