### ISSUE TITLE
How to import "from" statically from the JsonPath class?

### ISSUE THREAD

**Issue by Zilev** [jayway/rest-assured#611]
Hi, I'm trying to do something like this, bit is not working fine, I don't get how to import "from" statically from the JsonPath class, that says I should do here
```
// "from" is statically imported from the JsonPath class
List<String> bookTitles = from(response).getList("store.book.findAll { it.price < 10 }.title");
```
I'm having this error "cannot find symbol  symbol:   method from(java.lang.String)", someone would help me please?, thanks in advance :smile:

**Comment by johanhaleby** [comment]
The method is in class `com.jayway.restassured.path.json.JsonPath`. Please use the mailing list when asking questions in the future.
