### ISSUE TITLE
How to use di with rest assured?

### ISSUE THREAD

**Issue by favetelinguis** [jayway/rest-assured#620]
When trying using Cucumber and pico container to share a Response object between multiple cucumber steps i have not been able to do so.
The reason is that rest assured returns interfaces and to be able to use di i need a concrete instance.
Are there any solutions for gradually building up and asserting againt the same response object between given/when/then steps in cucumber ?

**Comment by johanhaleby** [comment]
I'm not sure I understand what you mean. The response object is returned as a response to a request. You can share it between multiple instances if you like. But a Response object that has not been created by REST Assured doesn't make any sense (i.e. I don't see why you want to create your own instance of it).

**Comment by favetelinguis** [comment]
Cucumber uses dependency injection inorder to share state between given/when/then steps when the steps are located in different classes. Cucumber creates one instance of each step class for each scenario. What I want to do is use springs @Autowire Response response so that this reponse will be shared between the different classes.

**Comment by johanhaleby** [comment]
You can't call an interface without an implementation so there must be an implementation somewhere. I might need to create a factory/provider or something similar (don't know what this concept is called in Pico) that allows you to set the Response object.
