### ISSUE TITLE
Add support for supplying the content-id and start-info for multipart/related requests  

### ISSUE THREAD

**Issue by hardeepkaur49** [jayway/rest-assured#623]
1)Currently rest-assured is ignoring the start-info from the contentType . For instance, below the start-info was supplied in the contentType but when the request was posted the same was ommitted . 

Request formed >
reqSpec.contentType("multipart/related; start-info=\"text/xml\"; boundary=\"=xzMLbCRFyWCyWsODxHhVYHLhVmk2aMaK\"")

Request posted >
Content-Type: multipart/related; boundary=xzMLbCRFyWCyWsODxHhVYHLhVmk2aMaK

Its necessary for me to supply the start-info .

2)Currently rest-assured doesn't allow to set the content-id . Its necessary in case of attachments for multipart/related requests .

**Comment by johanhaleby** [comment]
Thanks for reporting, I'll see what I can do. Please help out to make it happen faster.

**Comment by hardeepkaur49** [comment]
Hi Johan  ,

Can you please provide me update for the issue .

Thanks in advance .

**Comment by johanhaleby** [comment]
I've been on vacation so I haven't had a chance to look into it. I don't have too much experience with what you're requesting either so it would be really nice if you could help out. Either by providing a pull request or help out with design and knowledge when I find the time to implement it. Also do you know if this is supported by apache http client (when using the `org.apache.httpcomponents:httpmime` library which RA is using?).

**Comment by johanhaleby** [comment]
Also could you explain to me a bit more how multipart/related works so that I don't need to read the RFC? Especially:

1. How is it different from "normal" multipart requests?
1. What is content id and how/where would you like to specify it (in the RA API)?

**Comment by johanhaleby** [comment]
Are you willing to help out with this (at least answering my questions here) otherwise I'll close the issue?

**Comment by hardeepkaur49** [comment]
Found an alternative , Hence closing the issue ,

**Comment by hardeepkaur49** [comment]
Johan ,

Sorry I was on vacation and just returned . I was able to find an alternate
. So have closed the issue .

Thanks and Regards,
Hardeep

**Comment by johanhaleby** [comment]
Thanks for your feedback. Just curious, did you find a alternative within REST Assured or did you use something else? If so what did you use (if so perhaps I can look into that to improve RA)?
