### ISSUE TITLE
Documentation Related - need to do multiple times mvn install and mvn package

### ISSUE THREAD

**Issue by vikramvi** [jayway/rest-assured#624]
Please add below steps to make all test cases pass after downloading dependancies , which may take little longer

http://stackoverflow.com/questions/8563960/maven-command-to-update-repository-after-adding-dependency-to-pom

Thanks,
Vikram

**Comment by johanhaleby** [comment]
What do you mean?! You can easily build the project by just doing `mvn clean install`. If you want javadoc and source then just do `mvn clean javadoc:jar source:jar install`.

**Comment by vikramvi** [comment]
Thanks for clarification @johanhaleby.

 Can please add mvn clean install step for newcomers in documentation ?

Regards,
Vikram

**Comment by johanhaleby** [comment]
But why would newcomers need to build the javadoc and source themselves? It's available at maven central?

**Comment by vikramvi** [comment]
Thanks for clarification , closing this issue
