### ISSUE TITLE
Need Info - how to use this framework automating https://dev.twitter.com/rest/public

### ISSUE THREAD

**Issue by vikramvi** [jayway/rest-assured#625]
Hi @johanhaleby 

I've looked into "rest-assured-itest-java" but couldn't get going with simple test cases for twitter api like 
a> loggin in
b> get tweets
c> post tweets etc

can you please clarify where to mention twitter URL , mention access token , tokensecret , consumer key and secret

2nd query , I looked into OAuthITest.java but didn't understand which URL is getting called for authorization

Thanks in advance.

Regards,
Vikram

**Comment by johanhaleby** [comment]
I'm developing a generic REST test framework, I'm not giving away free consultancy for solving a broader problem. You need to read the twitter docs.
