### ISSUE TITLE
patch fails for when hashmap is passed to body( )

### ISSUE THREAD

**Issue by vikramvi** [jayway/rest-assured#628]
works below

given().headers("X-Access-Token",access_Token, "X-Client-ID",client_ID).
	                contentType("application/json; charset=utf-8").
	                body("{\"revision\":5,\"title\":\"PATCH-REQUEST\"}").  
	     when().
                       patch(APIUrl + "/lists/"+ list_id).
            then().
                     statusCode(200);

throws error 400 for hashmap

 Map<String, Object>  jsonAsMap = new HashMap<>();
		                    jsonAsMap.put("revision", "6");
	                            jsonAsMap.put("title", "ZZZZZZ");

	       given().headers("X-Access-Token",access_Token, "X-Client-ID",client_ID).
	                   contentType(JSON).
	                   body(jsonAsMap).
	       when().
                         patch(APIUrl + "/lists/"+ list_id).
           then().
                   statusCode(200);

Am I doing something wrong here or it's a bug ? I looked into PathParamITest.java for this example 

Please look into this

Thanks,
Vikram

**Comment by johanhaleby** [comment]
I suppose this should work, I'll look into it.

**Comment by johanhaleby** [comment]
I can't reproduce it, see my test [here](https://github.com/jayway/rest-assured/blob/master/examples/rest-assured-itest-java/src/test/java/com/jayway/restassured/itest/java/PatchITest.java#L83)

**Comment by vikramvi** [comment]
Thanks johanhaleby , have added below to pom.xml to fix issue.

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.2.4</version>
            <scope>test</scope>
        </dependency>
