### ISSUE TITLE
Unable to test null/empty path parameters

### ISSUE THREAD

**Issue by gigaSproule** [jayway/rest-assured#631]
As discussed on the [Google group](https://groups.google.com/forum/#!topic/rest-assured/6jl6vl-0zWI) , when testing null or empty path parameters, `java.lang.IllegalArgumentException: Path parameters were not correctly defined. Undefined path parameters are: paramName` is thrown.

It looks like RequestSpecificationImpl#findNamedPathParamValue line 1688 is calling trimToNull, so that is also returning null.

Example code:
```
    given() 
        .basePath("entity") 
        .pathParam(CLIENT_ID, "") 
        .pathParam(SECTION, "section") 
        .pathParam(UUID_TYPE, "uuidType") 
        .pathParam(UUID, "uuid") 
        .get("/{clientId}/{section}/{uuidType}/{uuid}") 
        .then() 
        .assertThat() 
        .statusCode(is(400));
```

The following code would work:
```
given() 
        .get("/entity//section/uuidType/uuid") 
        .then() 
        .assertThat() 
        .statusCode(is(400));
```

**Comment by johanhaleby** [comment]
Thanks for reporting

**Comment by johanhaleby** [comment]
I've now implemented this and pushed a new snapshot. Please try out version `2.8.1-SNAPSHOT` after having added the following repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

Please tell me if it works for you or not.

**Comment by gigaSproule** [comment]
That seems to be working now, or at least with the few tests I tried! Thanks very much for this.

**Comment by johanhaleby** [comment]
Thanks for your patience and for trying it out.

**Comment by vikramvi** [comment]
@gigaSproule please clarify how did you pass `null`  value, I don't want to pass `empty string` but `null` value itself as parameter.

**Comment by gigaSproule** [comment]
It's been a long time since I've seen this, but looking at my comments I couldn't pass null, just an empty string.

**Comment by vikramvi** [comment]
@gigaSproule Thanks for quick clarification.

**Comment by sudheerah** [comment]
@johanhaleby,
I was trying to pass path parameter as empty/null in cucumber api testing using restAssured.

e.g. when I call endpoint as >> http://localhost:8093/my-rest-call//instructions
(http://localhost:8093/my-rest-call/{path param}/instructions)

it's giving 404 But I expect 500. In postman it works as expected though

However if the null/empty path parameter at the end. like below I get 500 internal server error as expected.
e.g http://localhost:8093/my-rest-call/instructions/{path param}


I am using io.rest-assured:rest-assured:3.3.0
