### ISSUE TITLE
 Is there any options to disable/enable charset in content-type?

### ISSUE THREAD

**Issue by jshanaiah** [jayway/rest-assured#635]
My request looks like below 
 given().header("Content-Type", "application/ld+json")

At server end i receive content type as "application/ld+json; charset=ISO-8859-1".
Is there any options to disable/enable charset in content-type?

**Comment by johanhaleby** [comment]
Yes you can already do this, see documentation [here](https://github.com/jayway/rest-assured/wiki/Usage#avoid-adding-the-charset-to-content-type-header-automatically).

**Comment by jshanaiah** [comment]
Thanks for the information.

Apart from importing com.jayway.restassured.config.RestAssuredConfig . Is there any other imports ,

I keep getting "The method config() is undefined for the type"  and "The method encoderConfig() is undefined for the type ". I can only extend one class

**Comment by johanhaleby** [comment]
Yes you can statically import it from `EncoderConfig`

**Comment by jshanaiah** [comment]
Even after having both RestAssuredConfig  and EncoderConfig imports.

I keep getting "The method config() is undefined for the type" and "The method encoderConfig() is undefined for the type "

**Comment by jshanaiah** [comment]
public TestPostEventRest() {
		RestAssured.baseURI = "http://localhost";
		RestAssured.port = 8080;
		RestAssured.config = config(config().encoderConfig(encoderConfig().appendDefaultContentCharsetToContentTypeIfUndefined(false));
	}

**Comment by johanhaleby** [comment]
The first config method is statically imported from `RestAssured` itself

**Comment by johanhaleby** [comment]
* `com.jayway.restassured.config.EncoderConfig.encoderConfig`
* `com.jayway.restassured.RestAssured.config()`

**Comment by jshanaiah** [comment]
Thanks for the suggestion. Above suggestion helped me to resolve the issue.

given().header("Content-Type", "application/ld+json").config(com.jayway.restassured.RestAssured.config().encoderConfig(com.jayway.restassured.config.EncoderConfig.encoderConfig().appendDefaultContentCharsetToContentTypeIfUndefined(false)))
