### ISSUE TITLE
Expect Content-Type to be empty or to not exist

### ISSUE THREAD

**Issue by Signus** [jayway/rest-assured#636]
In certain instances where I expect a malformed response (such as a improperly built 401 response), I should also expect the Content-Type field in the header to not exist rather than expect a certain type, that way I don't see this in my test results:

    0    [main] WARN  com.jayway.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder    
    Could not parse content-type: Response does not have a content-type header

This is not a very big deal since it's passed over and it does not invalidate my tests, but I do want the ability to expect a null-or-empty Content-Type for these responses. Something like:

    expect()
        .statusCode(401)
	.given()
	    .header(badHeader)
	    .contentType(ContentType.NAN)
	.when()
	    .get(APP_URL);

Given my brief reading of the docs - my suggestion, if possible, is to add NAN (or similarly named) to the Enum list. However the only problem there is that the header itself doesn't exist in these kinds of responses, so you have to ensure that HttpResponseContentTypeFinder considers this case.

**Comment by johanhaleby** [comment]
Can't you do `.contentType(nullOrEmptyString())`?

**Comment by Signus** [comment]
Not that I can tell. ContentType evaluates as a Enum and the only string that it can accept is to return the ContentType based on a string like "application/json" to return JSON as a ContentType.

**Comment by johanhaleby** [comment]
Sorry I misunderstood, I thought you ment that you wanted to verify that the content-type was not present in the response (and if so you can use that hamcrest matcher). So you want to exclude the content-type header from the request? If you do:

```java
given(). 
		config(RestAssured.config.encoderConfig(EncoderConfig.encoderConfig().appendDefaultContentCharsetToContentTypeIfUndefined(false))).
        contentType(""). ..
```

REST Assured will send an empty content-type header: `Content-Type: ` (i.e. the content-type header still exists but is empty). Will that work for you?

**Comment by Signus** [comment]
My apologies for not explaining it very well. What I do mean is that want the ability to verify it was not present in a response to understand when our responses are malformed (missing Content-Type). 

This being said, I ultimately want the ability to pass/fail a test based on whether Content-Type exists in the header or not (some special cases either myself or other users would maybe want to remove it and expect that it not be there).

**Comment by johanhaleby** [comment]
Ok but wasn't that what I tried to explain [here](https://github.com/jayway/rest-assured/issues/636#issuecomment-173826663)? You should be able to do so by using that Hamcrest matcher?

**Comment by Signus** [comment]
The problem there is something like `nullOrEmptyString()` takes a string and returns a boolean. ContentType is a RequestSpecification (same as `given()`) that takes a string.

You have tests that validate that a ContentType won't match when expected to have a different value of an enum. You can't **expect** to check for a null or empty ContentType to be **given**. 

Example: ContentTypeTest.java

```java
@Test public void
    content_type_doesnt_match_when_expected_content_type_is_null() {
        // Given
        final String expected = null;

        // When
        boolean matches = ContentType.JSON.matches(expected);

        // Then
        assertThat(matches, is(false));
    }
```

As expected:

```java
// true
ContentType.JSON.matches("application/json")

// false
ContentType.JSON.matches("")
```

The ContentType can be null according to the parser, however the hamcrest matcher for `expect()` or `given()` only evaluates a string based on the enum for which the following charsets are available (ContentType.java):

```java
ANY("*/*"),
TEXT("text/plain"),
JSON("application/json", "application/javascript", "text/javascript"),
XML("application/xml", "text/xml", "application/xhtml+xml"),
HTML("text/html"),
URLENC("application/x-www-form-urlencoded"),
BINARY("application/octet-stream");
```

To my knowledge you cannot (easily) apply a null to an enum, so my suggestion would to be to have whatever extracts the Content-Type transpose null to an empty string. The enum could then add:

```java
...,
...,
NONE("");
```

To allow for the possibility testing against responses that either have an empty Content-Type or no Content-Type within the header.

I'm simply looking for what is available in the library, and if it's not then I care about how to make it fit best within the library so any PR I submit adds value to the project.

**Comment by johanhaleby** [comment]
Sorry but I still don't understand. Here's a simple test that shows that you can indeed verify empty content-types:

```java
@Test public void
can_assert_empty_or_null_content_type() {
    given().
            filter((requestSpec, responseSpec, ctx) -> new ResponseBuilder().setStatusCode(200).setHeader("Some", "Value").setBody("Test").build()).
    when().
            get("/something").
    then().
            contentType(isEmptyOrNullString());
}
```

It's using the `isEmptyOrNullString()` Hamcrest matcher.

**Comment by Signus** [comment]
I think my problem was that I was using it in the context of `given()` which gives me:

```
[ERROR] (argument mismatch; org.hamcrest.Matcher<java.lang.String> cannot be converted to com.jayway.restassured.http.ContentType)
```

However in the context of `then()` the Hamcrest matcher for `isEmptyOrNullString()` works perfectly. That is my fault for that disconnect. I will look more closely into how that works for my own education.

Thank you for your help!
