### ISSUE TITLE
Multipart not working!

### ISSUE THREAD

**Issue by dustin-H** [jayway/rest-assured#638]
Hi there,

I have this test code, which is pretty much the same as in your docs.
```
InputStream is = getClass().getResourceAsStream("/upload1.png");
given().
    multiPart("file", "myFile.png", is, "image/png").
    when().
    post("/form/testFormId");
```

In my Spring app I am reading the HttpServeletRequest and always receive 0 parts:

```
@RequestMapping(path = "/form/{id}", method = RequestMethod.POST, headers = {"content-type=multipart/form-data"})
@ResponseBody
public ResponseEntity receivePostMultipart(@PathVariable String id, HttpServletRequest request) throws IOException, ServletException, Exception {
        Collection parts;
        parts = request.getParts();
        LOG.debug("PARTS.SIZE! " + parts.size());
}
```

I am using Java 8 and rest-assured 2.8.0.

May this is a bug? I already tested my application with a default html form with "multipart/form-data" and it worked.

Thanks, Cheers
Dustin

**Comment by johanhaleby** [comment]
Is this still an issue?

**Comment by dustin-H** [comment]
Not sure right now. As I left the project about 3 months ago it was still an issue.

**Comment by johanhaleby** [comment]
Thanks for your comment. There's actually tests in the RA code base that should test this so I actually do think it works. Reopen or file a new issue if you run into something similar again. I'll close the issue for now.
