### ISSUE TITLE
Link to GPath doc broken in "Getting started"

### ISSUE THREAD

**Issue by rhuss** [jayway/rest-assured#640]
The link to the **GPath** documentation on the Wiki page "Getting started" is broken. I would have sent a PR but this isn't supported by GitHub for Wikis (and the Wiki is not open for editing).

I suggest to update the link e.g. to http://docs.groovy-lang.org/latest/html/documentation/core-semantics.html#gpath_expressions

**Comment by rhuss** [comment]
Same broken link in the "Usage" page, btw.

**Comment by rhuss** [comment]
While we are on it, in "Usage" the old syntax is sometimes referred to as "given / expect / then" instead of "given / expect / when"

**Comment by johanhaleby** [comment]
Thanks for pointing this out. I've fixed it now!
