### ISSUE TITLE
how to generate 400 from server

### ISSUE THREAD

**Issue by tique** [jayway/rest-assured#644]
Hi, 
I am trying to send a request that generates a bad request [400] from the server so I can check that the error messages are correct. 

To do this I was going to try this [suggestion](http://blog.williamhilsum.com/2012/03/how-to-generate-http-400-error-from.html) and add a "%" to the path. 

Although when I attempt this with `urlEncodingEnabled = false` I get a `URISyntaxException: Malformed escape pair` and the test fails. 

Is there any way I can do this with rest assured? or write a test to generate a bad request somehow?
Thanks

**Comment by johanhaleby** [comment]
No, you cannot provide a bad URI like that. It needs to be a valid URI but something that is invalid to your application (which is specific to your app).
