### ISSUE TITLE
Add support for changing value of a header in RequestSpecBuilder class either by providing setHeader or removeHeader method

### ISSUE THREAD

**Issue by crosslives** [jayway/rest-assured#648]
I would like to change the value of a header specifically in my case, the authorization header for testing various cases. Currently, I only see adding multiple values to the same header which I do not want to do since it is an authorization header or else I have to have a separate RequestSpecBuilder per test which is too much repetition. It would be great if I can just have a setHeader method which overwrites the header value for the given header name or have a removeHeader method which removes the header from the requestSpecBuilder and I can add it again using addHeader.

Please let me know if there is already a way to do this and I have missed it. Thank you!!

**Comment by johanhaleby** [comment]
You can use the [HeaderConfig](http://static.javadoc.io/com.jayway.restassured/rest-assured/2.8.0/com/jayway/restassured/config/HeaderConfig.html) to configure if headers should be merged or overwritten. I've also updated the [docs](https://github.com/jayway/rest-assured/wiki/Usage#header-mergingoverwriting).

**Comment by thomlar** [comment]
Don't know if this warrants a new issue, but a removeHeader method would be useful, I needed to remove the Accept header and using the overwriter at best nets you an empty Accept header.

I ended up injecting into the httpclient, but still, more control over headers wouldn't be bad.

**Comment by johanhaleby** [comment]
@thomlar you can already do this by using a [filter](https://github.com/rest-assured/rest-assured/wiki/Usage#filters).

**Comment by thomlar** [comment]
@johanhaleby my bad, I was running an older version that did not have it, unfortunately after playing around with the newer version, it appears that RestAssured adds it own Accept header [if none is found](https://github.com/rest-assured/rest-assured/blob/f0ba96b58c21f28b5f8a40c75a669152ff3c0e85/rest-assured/src/main/groovy/io/restassured/internal/RequestSpecificationImpl.groovy#L1140) but thanks for the help.

**Comment by johanhaleby** [comment]
Yes it does. Is that a problem for you? If so please open another issue and we can discuss it.

**Comment by thomlar** [comment]
It's not really a big issue for me, but I think it would be nice to have anyway, so I've opened an issue about it.
