### ISSUE TITLE
Does it support 2 legged call in Oauth

### ISSUE THREAD

**Issue by aniket-21** [jayway/rest-assured#651]
I see that Oauth method accepts Consumer Key, Secret, Token and Token Secret.
How can I make a 2 legged call ? Will it work if I pass Token and Token secret as empty strings?

**Comment by johanhaleby** [comment]
Not sure actually, please try it out and tell me if it works or not.

**Comment by aniket-21** [comment]
sure, if not, I would be glad to submit a PR

**Comment by johanhaleby** [comment]
I would be glad to accept it :)

**Comment by aniket-21** [comment]
Just checked, it doesn't work w/o access token. I will send a PR for this once fixed

**Comment by aniket-21** [comment]
@johanhaleby , this seems to be a problem with scribe library itself, Whenever a blank access token is passed , oauth_token parameter needs to be added to base string with null value.
but the way its implemented in scribe oauth lib is it skips that parameter resulting into a diff base string and hence a different signature.

// Do not append the token if empty. This is for two legged OAuth calls.
 if (!token.isEmpty()) {
       request.addOAuthParameter(OAuthConstants.TOKEN, token.getToken());
 }

I am getting different implementations the more I search. For example
http://oauth.googlecode.com/svn/code/javascript/example/signature.html --> works like scribe
http://nouncer.com/oauth/signature.html --> Doesn't work like scribe (http://oauth.net/core/1.0/#rfc.section.9.1.1)
http://oauthbible.com/ -> Suggests to added oauth_token parameter even if its empty

**Comment by johanhaleby** [comment]
Thanks a lot for your investigation. What would you suggest to be the way forward?

**Comment by aniket-21** [comment]
I have logged a bug in scribe project https://github.com/scribejava/scribejava/issues/625
Lets see what they have to say about it. If they fix it, it would be great!
In case they do, we may have to point to update maven repo of scribe

<dependency>
    <groupId>com.github.scribejava</groupId>
    <artifactId>scribejava-apis</artifactId>
    <version>2.2.2</version>
</dependency>

**Comment by aniket-21** [comment]
Temporary hack is to explicitly add oauth_token parameter (if empty) in process method of AuthConfig before the request is sent for signing

**Comment by aniket-21** [comment]
I tried, it works now for 2 legged APIs

**Comment by johanhaleby** [comment]
Cool. Should we include it in RA? If so could you make a pull request?

**Comment by aniket-21** [comment]
We got the fix in scribe lib :) we should point RestAssured to use latest scribe libs

**Comment by johanhaleby** [comment]
Nice! But I don't suppose it's released yet?

**Comment by aniket-21** [comment]
Not yet, I will create a PR once it's released.

**Comment by johanhaleby** [comment]
Great!! Thanks a lot for you help so far.

**Comment by aniket-21** [comment]
@johanhaleby , The fix we talked about is released now. I tried updating the Scribe dependencies and everything looks good so far.
Now regarding the fix for AccessToken, I wish to have flexibility of whether the empty access token needs to be considered as part of base string or not.
Where do you think , user should be able to set this flag when using RestAssured APIs?

**Comment by johanhaleby** [comment]
Not sure, do you have any suggestions?

**Comment by aniket-21** [comment]
Sending through oauth spec would be a really bad idea, so I was checking for RestAssured config and other config files. Still trying to understand how they work. Any idea if we can use a config file to set/tweak this as per the requirement?

**Comment by johanhaleby** [comment]
Yeah config files might work, but could you please explain what an "empty access token" mean? I don't suppose you just mean this?

```java
 given().auth().oauth2("").
```

**Comment by aniket-21** [comment]
For a 2 legged call, when the access token is empty (mainly for oauth1.0) , the "oauth_token" param still needs to be added to base string with value as "". So if boolean value passed/set is true, we will include this parameter, if its set to false, we wont
The config param can be like "isEmptyOAuthTokenParamRequired". Default can be False as its set to False in Scribe as well.

**Comment by johanhaleby** [comment]
Ok, when you say "mainly for oauth 1" do you mean that this also affects oauth2? 

If so I think it would be a good idea to add a new config, OAuthConfig or something similar where `isEmptyOAuthTokenParamRequired` could be included. If you like I can create the config but perhaps you could help out with the implementation (or at least point me in the right direction) of where to apply this in scribe? I suppose it should be added somewhere in `com.jayway.restassured.internal.http.AuthConfig`?

**Comment by aniket-21** [comment]
No this wont affect oauth2 in anyway. I have tried exactly the same things you have mentioned. Create an OauthConfig file,  added a boolean field which is default set to false and can be configured to be true. 
This boolean value will be returned from overridden method  isEmptyOAuthTokenParamIsRequired() in class Oauth10aService when processed method of AuthConfig id called.

Issue I am facing is that even if I set the config value, it doesn't seem to flow down till the AuthConfig.
I am doing something wrong.

May be you can help setting up config file with just one boolean value and guide me how to use it in AuthConfig?

**Comment by johanhaleby** [comment]
Sure I can do this, I'll tell you when it's done.

**Comment by johanhaleby** [comment]
I've added a new config and it's now supplied to the AuthConfig class. I've published this to master.

**Comment by aniket-21** [comment]
Cool! I will try to integrate my changes now
