### ISSUE TITLE
[Need clarification] Does Rest assured supports database verification?

### ISSUE THREAD

**Issue by talktokets** [jayway/rest-assured#654]
Hi,

I am new to API testing and to rest-assured as well. I just wanted to know whether rest-assured can be used to test database as well or not.

Let me explain the situation in brief:

User makes a POST call and then in database the data is created.
Now I need to check whether the same data is inserted in the database or not. For this I am thinking to use a database connection in the script which will verify the actual data from the database and the returns the result.

Any help on this would be highly appreciated.

Thanks in advance!

**Comment by thekingnothing** [comment]
I'm not sure, but seems to me, better solution for you will be use [dbunit](http://dbunit.sourceforge.net/). 

The main purpose of DBUnit it's prepare DB state for integration tests, but it also could be used to check changes which has been made by a test.

**Comment by johanhaleby** [comment]
No RA is not concerned with database testing, this is out of scope for the project. As @thekingnothing says, dbunit or something similar is what you should use.

**Comment by talktokets** [comment]
@thekingnothing @johanhaleby Thanks for your help and reply! much appreciated.
