### ISSUE TITLE
Standard new JsonPath(string) will round decimal values

### ISSUE THREAD

**Issue by emmanuelrflores** [jayway/rest-assured#655]
Out of the box using new JsonPath(string) will round decimal values. For example

The values returned from a call are:

```
    {
        "floatVal1" : 88257020.93,
        "floatVal2" : 32783049.61,
        "latitude" : 35.12496,
        "longitude" : -106.54691,
        "float3" : 0.55,
    }
```

When I pass the string values into JsonPath, e.g.,`new JsonPath(jsonString)` the values are now:

```
    {
    	"floatVal1": 88257024.0, 
    	"floatVal2": 32783050.0, 
    	"latitude": 35.12496, 
    	"longitude": -106.54691, 
    	"float3": 0.55, 
    }
```

You can get over doing the following
`.using(new JsonPathConfig(JsonPathConfig.NumberReturnType.BIG_DECIMAL))`

But you shouldn't have to do the extra configuration to get the actual values in your data.

**Comment by johanhaleby** [comment]
The conversion looks like this (in `com.jayway.restassured.internal.path.json.ConfigurableJsonSlurper`):

![image](https://cloud.githubusercontent.com/assets/187029/13553582/a06990a2-e38e-11e5-8b9d-2b33a1d14915.png)

Is there a better way to convert from BigDecimal to float or double without loosing precision? Are the values represented correctly when using `NumberReturnType.BIG_DECIMAL`?

**Comment by emmanuelrflores** [comment]
Yes, values are represented correctly when using `NumberReturnType.BIB_DECIMAL`.

Maybe it would be a safer bet to always use double unless you're absolutely sure the value can fit inside a float.

I'm curious about the logic of `result > Float.MAX_VALUE`. Isn't `Float.MAX_VALUE` passed the point where you would start losing precision anyways?

**Comment by johanhaleby** [comment]
Hmm not sure when you start loosing precision. Do you know? If so we could
change the "cut off". We can't always return double since that'll break
backend compatibility.

måndag 7 mars 2016 skrev Emmanuel <notifications@github.com>:

> Yes, values are represented correctly when using
> NumberReturnType.BIB_DECIMAL.
>
> Maybe it would be a safer bet to always use double unless you're
> absolutely sure the value can fit inside a float.
>
> I'm curious about the logic of result > Float.MAX_VALUE. Isn't
> Float.MAX_VALUE passed the point where you would start losing precision
> anyways?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jayway/rest-assured/issues/655#issuecomment-193371353>
> .
>


-- 
Sent from my phone

**Comment by johanhaleby** [comment]
-backend +backward

måndag 7 mars 2016 skrev Johan Haleby <johan.haleby@gmail.com>:

> Hmm not sure when you start loosing precision. Do you know? If so we could
> change the "cut off". We can't always return double since that'll break
> backend compatibility.
>
> måndag 7 mars 2016 skrev Emmanuel <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
>
>> Yes, values are represented correctly when using
>> NumberReturnType.BIB_DECIMAL.
>>
>> Maybe it would be a safer bet to always use double unless you're
>> absolutely sure the value can fit inside a float.
>>
>> I'm curious about the logic of result > Float.MAX_VALUE. Isn't
>> Float.MAX_VALUE passed the point where you would start losing precision
>> anyways?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jayway/rest-assured/issues/655#issuecomment-193371353>
>> .
>>
>
>
> --
> Sent from my phone
>


-- 
Sent from my phone

**Comment by emmanuelrflores** [comment]
Honestly I don't know what that cut off is. 

It sounds like there really isn't a solution other than forcing `NumberReturnType.BIG_DECIMAL`.

**Comment by nomiSheikh** [comment]
Thanks emmanuelrflores for posting the tip. It saved me from a lot of hassle.

**Comment by lakshmithampi** [comment]
Thanks emmanuelrflores....You helped me a lot
