### ISSUE TITLE
multiPart file Post call failing with updated version past 2.6.0 and up

### ISSUE THREAD

**Issue by emmanuelrflores** [jayway/rest-assured#657]
I updated my pom.xml to the latest version 2.9.0 and started getting the following error. 

```
java.lang.NoSuchMethodError: org.apache.http.entity.ContentType.withParameters([Lorg/apache/http/NameValuePair;)Lorg/apache/http/entity/ContentType;
	at org.apache.http.entity.mime.MultipartEntityBuilder.buildEntity(MultipartEntityBuilder.java:219)
	at org.apache.http.entity.mime.MultipartEntityBuilder.build(MultipartEntityBuilder.java:240)
	at org.apache.http.entity.mime.MultipartEntityBuilder$build$16.call(Unknown Source)
	at com.jayway.restassured.internal.multipart.RestAssuredMultiPartEntity.getEntity(RestAssuredMultiPartEntity.groovy:58)
```

I get the same error if I switch to 2.8, 2.7, and 2.6. 

I don't have any special set up for rest-assured or the TestNG framework. The below is how it's set up in the pom.xml file. 
```
	<dependency>
		<groupId>org.codehaus.groovy</groupId>
		<artifactId>groovy-all</artifactId>
		<!-- Needs to be the same version that REST Assured depends on -->
		<version>2.4.4</version>
		<scope>test</scope>
	</dependency>

        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>2.6.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>2.6.0</version>
            <scope>test</scope>
        </dependency>
	<dependency>
		<groupId>commons-codec</groupId>
		<artifactId>commons-codec</artifactId>
		<version>1.4</version>
	</dependency>
	<dependency>
		<groupId>org.testng</groupId>
		<artifactId>testng</artifactId>
		<version>6.9.10</version>
		<scope>test</scope>
	</dependency>
```

I did find the following [issue you responded to](https://groups.google.com/forum/#!topic/rest-assured/oq8Oc-6R6tA) and I don't have any other dependencies to `Apache HTTP client` as you've mentioned. Everything goes strictly through Rest-assured. 

Is there anything additional I should be requiring or looking into? Let me know if there's additional information I should provide. 

Also, please let me know if this is the proper forum for help with these kind of issues.

**Comment by johanhaleby** [comment]
Thanks for reporting. Could you provide some code that shows what you're doing?

**Comment by emmanuelrflores** [comment]
Here is the call where the error is coming from:

```
        Response response = given()
                .header("Accept", "application/json")
                .queryParam("token", accessToken)
                .multiPart("body", new File(getClass().getResource("/csv/"+locationFileName).getFile()))
                .when()//.log().all()
                .post(URI.UPLOAD_DATA_FILE.getUri())
                .then()//.log().all()
                .contentType(ContentType.JSON)
                .statusCode(200)
                .assertThat()
                .body( matchesJsonSchemaInClasspath("json-schema/v2-upload-post.json"))
                .extract()
                .response();
```

I noticed under the [change notes](https://github.com/jayway/rest-assured/wiki/ReleaseNotes26#other-notable-changes) for v2.6 there were updates to the multipart call. Do I need to change the configuration for the file now?

**Comment by johanhaleby** [comment]
Hmm I find it quite strange that you run into a `java.lang.NoSuchMethodError`. I suspect that you are not using Apache HTTP Client 4.5.1 (that RA depends on). I can confirm that the method you're missing is indeed there. I've debugged your example and I can step into the `ContentType.withParameters` without any problems.

**Comment by emmanuelrflores** [comment]
It looks like there's another dependency that uses Apache HTTP Client 4.3.5 or something. Since that dependency was sitting before RA, the Maven would use the first HTTP Client it hit. I wasn't aware java did that. Very interesting.
