### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by brucampos88** [jayway/rest-assured#663]
Hi!
I'd like to contribute to this project.
Do you guys have some guide that explain how to contribute?

Thanks.

**Comment by johanhaleby** [comment]
Hi burno! 

Thanks for showing interest in the project. You could start off by looking at the issues and try to provide pull requests for some of the open issues. That would be a good start and it would allow you to get into the code. Feel free to ask me questions regarding design decisions etc. We don't have any specific developer documentation so the code and usage guide would be a good place to start. You should be able to just open the project root pom.xml in Intellij and you should be good to go.

Regards
/Johan
