### ISSUE TITLE
cannot set timeout as I followed the user guide

### ISSUE THREAD

**Issue by qianyiliushang** [jayway/rest-assured#664]
I just cannot set the request timeout,which the user guide says

```
given().
        body("a string").
when().
        async().with().timeout(20, TimeUnit.SECONDS).post("/stringBody").
then().
        body(equalTo("a string"))
```
there's no method called async

maybe the document is outdated?

**Comment by johanhaleby** [comment]
This is only available in the Spring MockMVC module

**Comment by qianyiliushang** [comment]
@johanhaleby 

what if I did not use Spring MockMVC module, any other way to set connection timeout?
And the default value of timeout is ?
