### ISSUE TITLE
POST request with heratic behavior

### ISSUE THREAD

**Issue by sfmarty** [jayway/rest-assured#665]
Hello

When running my POST request (exactly the same every time) I face either:

- No error
- Error of the type: "Content type 'application/x-www-form-urlencoded;charset=ISO-8859-1' not supported"
- Error of the type: "Required request body is missing"

with absolutely no pattern, sometimes I have no error, sometime the first type error and sometime the second type error.

My post request looks like:

given().
            headers("Accept", "*/*").
            queryParam("myStringParam", "myParamValue")
            queryParam("myJSONParam",  getContentJSONFile("myJSONFile.json").
when().
            post("mypostrequest").
then().
            statusCode(200);

Thanks in advance for enlighten me on this.

Seb

**Comment by johanhaleby** [comment]
Hmm could it be something wrong with the server? Or are you running your tests in parallell?

**Comment by johanhaleby** [comment]
No response so closing issue
