### ISSUE TITLE
Can I run the rest assured test using junit ?

### ISSUE THREAD

**Issue by jaydeepc** [jayway/rest-assured#666]
Basically this is for reporting and I want the runner to give me a json report, which I can send through my JSON parser to get a nice looking HTML report

**Comment by johanhaleby** [comment]
ok? Does this have anything to do with REST Assured?

**Comment by jaydeepc** [comment]
Thats what I am asking. If I can run using junit, I can do this in JUNIT. But I am not able to run the example tests using junit from command line

**Comment by johanhaleby** [comment]
You can use JUnit or TestNG or another test library. How to configure these libraries are out of scope of the rest assured project.
