### ISSUE TITLE
RequestSpecBulider addMultiPart cannot use MultiPartSpecification

### ISSUE THREAD

**Issue by RocketRaccoon** [jayway/rest-assured#669]
Hi!

Please, make RequestSpecBuilder#addMultiPart accept MultiPartSpecification as argument

**Comment by johanhaleby** [comment]
It already does:

```java
/**
     * Specify a multi-part specification. Use this method if you need to specify content-type etc.
     *
     * @param multiPartSpecification Multipart specification
     * @return The request specification
     */
    RequestSpecBuilder addMultiPart(MultiPartSpecification multiPartSpecification) {
        spec.multiPart(multiPartSpecification);
        return this;
    }
```

**Comment by RocketRaccoon** [comment]
It is not resloved in IDEA, I got error for folowing expression:

        RequestSpecBuilder builder = new RequestSpecBuilder();
        MultiPartSpecification mps = new MultiPartSpecBuilder("string").build();
        builder.addMultiPart(mps);

**Comment by johanhaleby** [comment]
Are you using the latest version?

**Comment by johanhaleby** [comment]
Oh now I see that it's a bug in the code. The method was added several years ago but it was package private. I'll fix it.

**Comment by johanhaleby** [comment]
I've now deployed a new snapshot that should address this issue. Please try version `2.9.1-SNAPSHOT` after having added the following Maven repository:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by RocketRaccoon** [comment]
Thanks, will check it
