### ISSUE TITLE
For multipart requests set boundary in contentType is overrided when sent

### ISSUE THREAD

**Issue by RocketRaccoon** [jayway/rest-assured#670]
Hi

When I'm trying to set boundary for multipart manually, e.g.
`given() .contentType("multipart/mixed; boundary=" + BOUNDARY)`
it is overrided by another value (I'm cheking outgoing value via WireShark).

Setting boundary with apache httpclient `MultipartEntityBuilder#setBoundary` works fine, but I want to create multipart request using Rest Assured only.

**Comment by johanhaleby** [comment]
What does the code look like if you're only using apache httpclient?

**Comment by RocketRaccoon** [comment]
Like this one:

        HttpEntityEnclosingRequestBase req = SimpleHttpClient.put(resourceUri);
        MultipartEntityBuilder entityBuilder = MultipartEntityBuilder.create();
        entityBuilder.setBoundary(BOUNDARY)
                .setMode(HttpMultipartMode.STRICT)
                .setCharset(UTF_8);
        entityBuilder.addPart("json", new StringBody(ids, ContentType.APPLICATION_JSON));
        HttpEntity entity = entityBuilder.build();
        req.setEntity(entity);
        req.addHeader("Content-Type", CONTENT_TYPE_MULTIPART);

**Comment by johanhaleby** [comment]
I've now deployed a new snapshot that should address this issue. Please try version `2.9.1-SNAPSHOT` after having added the following Maven repository:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

It's also possible to specify a default boundary by using the `MultiPartConfig`.
