### ISSUE TITLE
Suppport for setting session attributes in MockMvcRequestSpecification

### ISSUE THREAD

**Issue by sneyyar** [jayway/rest-assured#671]
SpringMockMvc supports adding custom objects to session before sending the request.  This is critical to test Controllers implementing session management. It would be really helpful to add sessionAttribute(name, Object) to MockMvcRequestSpecification interface and link with corresponding feature supported by Spring mock mvc

**Comment by sneyyar** [comment]
I already have this fixed to my local clone . Would be more than happy to check this in to master branch.

**Comment by johanhaleby** [comment]
It would be great if you want to provide a pull request for this.

**Comment by sneyyar** [comment]
I created a pull request with my fix. https://github.com/jayway/rest-assured/pull/673

**Comment by johanhaleby** [comment]
I did some changes to make session attributes behave the same way as the other parameters/attributes. Thanks for your help-

**Comment by sneyyar** [comment]
You are welcome. It would be nice if we could read objects (eg: userInfo)
from session after a get or post request. We need to inject userInfo into
session (session.sessionAttr(userInfo)  ) before invoking the next request.

Do we support this feature as of now ? If not, would you like to open
another issue ?

**Comment by johanhaleby** [comment]
Perhaps you vould open another issue so that we can discuss it there?

**Comment by sneyyar** [comment]
Sure. I can open another issue if springMvc supports ability to retrieve
objects from session.
