### ISSUE TITLE
How to Simulate Different Network Speeds in Rest-Assured

### ISSUE THREAD

**Issue by tigerqiu712** [jayway/rest-assured#672]
In most cases, mobile device users access the internet via their cellular operator network. The coverage will vary depending on their location, meaning the connection speed will vary. It is vital to ensure that your website or application can fully handle mobile and tablets - even when they have different internet connection speeds.
how to do this by controlling the bandwidth of Rest-Assured.

As i know meter have done for this scenario， please see https://blazemeter.com/blog/how-simulate-different-network-speeds-your-jmeter-load-test
 when we can supports this  scenario?

**Comment by johanhaleby** [comment]
Not sure if this is something the REST Assured should concern itself with. RA is not a tool for performance testing but rather for API testing.

**Comment by tigerqiu712** [comment]
hi johanhaleby ,
     yes ,RA not a performance  testing tool ,but the API should be measure Different Network Speeds to make sure the API can work well .

**Comment by johanhaleby** [comment]
Hmm RA can already _measure_ the "network speed" if you use [time](https://github.com/jayway/rest-assured/wiki/Usage#measuring-response-time)

**Comment by johanhaleby** [comment]
Closing due to lack of input and I think it's out of scope for the rest assured project.
