### ISSUE TITLE
using a Json file in Rest-assured for payload

### ISSUE THREAD

**Issue by bhaskarHub** [jayway/rest-assured#674]
I have a  JSON file to be POST as payload for a rest api call for testing purposes. I tried something like :

```
    public void RestTest() throws Exception {
    File file = new File("/Users/bmishra/Code_Center/stash/experiments/src/main/resources/Search.json");
    String content = null;

    given().body(file).with().contentType("application/json").then().expect().
            statusCode(200).
            body(equalTo("true")).when().post("http://devsearch");


}
```

and get error as :

`java.lang.UnsupportedOperationException: Internal error: Can't encode /Users/bmishra/Code_Center/stash/experiments/src/main/resources/Search.json to JSON.`

I can run by reading the file and passing the body as string and that works but I see i can directly pass the file object and this doesn't work.

**Comment by johanhaleby** [comment]
Thanks for reporting. I've started working on this now.

**Comment by bhaskarHub** [comment]
cool. If I get a patch quickly that would just be awesome :)

**Comment by johanhaleby** [comment]
It should be fixed now so I've now deployed a new snapshot that should address this issue. Please try version `2.9.1-SNAPSHOT` after having added the following Maven repository:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by bhaskarHub** [comment]
Just tested and it looks GOOD thanks.

**Comment by johanhaleby** [comment]
Great! Thanks for trying it out.

**Comment by praveen-aldur** [comment]
Im facing similar issue with PATCH request..

**Comment by johanhaleby** [comment]
@praveen-aldur Could you give me some more details? What does your test and payload look like?

**Comment by praveen-aldur** [comment]
![image](https://cloud.githubusercontent.com/assets/1721648/19240990/59f18c9a-8f2a-11e6-96ca-c3fedc935c82.png)


My TEST code: 

	public void updatePreferences(){
		
//	    String preference_json  = new JsonPath(RestUtil.getFile("updatePreferences.json")).using(new JsonPathConfig("ISO-8859-1")).prettify();
		
//		File file = RestUtil.getFile("updatePreferences.json");

		Header header = new Header("Content-Type", "application/json");

		Response res  = given()
								 .log()
								 .all()
								 .header(header)
								 .request()
						    	 .body("{\r\n  \"IsOnlinePricingActive\": false,\r\n  \"PreferredStore\": 4,\r\n  \"DefaultShoppingListId\": xxxxxx,\r\n  \"CommunicationPreferences\": {\r\n    \"FreshNews\": true,\r\n    \"OpinionPanel\": false,\r\n    \"WineNews\": true\r\n  }\r\n}")
								 .patch("/preferences?api-version=1.1 HTTP/1.1");
								 
		System.out.println(res.prettyPrint());
								 
	}


Response Logs: 
![image](https://cloud.githubusercontent.com/assets/1721648/19240793/951a3548-8f29-11e6-8acf-7735612ede39.png)

**Comment by johanhaleby** [comment]
I can see that you're using some for of Authentication/Authorization headers in your screenshots which are not present in REST Assured. You probably need to define them as well.

**Comment by Harirangan** [comment]
I am kinda designing page-object based automation framework with help of RA. I am getting "body can not be null" error when i pass the payload to a class which actually posts the request.When i post the request from parent class itself, it works fine.Please help on this.

Parent class:
	File file_location = new File("C:/Users/ranganah/RWS/src/Requests/GetEmployeedetails.json");
	String uri="http://localhost:8080/SpringREST/rest/emp/create";
	Newemployee obj=new Newemployee(file_location,uri);

Child:
public class Newemployee {	
	public String uri_class;
	public File thefile;
	public Newemployee(File file_loc,String uri){
		uri_class=uri;
		thefile=file_loc;
	}	
Response response=given().body(thefile).with().contentType("application/json").accept("application/json").post(uri_class);			
	String bodystring=response.getBody().asString();
	JsonPath jsonPath =JsonPath.from(bodystring);
.
.
.
Error:-
java.lang.IllegalArgumentException: body cannot be null

**Comment by Shaindil** [comment]
Can we do the same for response validation also...like passing file containing response json payload?

**Comment by Styris** [comment]
@johanhaleby @bhaskarHub I added this to my pom.xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>

Could you please paste what else I need to paste in the pom.xml (dependency?) to make this work.
Thanks!

**Comment by Styris** [comment]
@bhaskarHub @praveen-aldur I tried adding that piece to the POM.xml. I run my test but my Response output is "io.restassured.internal.RestAssuredResponseImpl@68b6f0d6" which does not seem to be the correct response. 
Is there something else I'm missng somewhere?
File file = new File("/Users/Kbay/IdeaProjects/RESTproj/CreateAccount.json");
        String content = null;
        Response resss = given().headers(headers).when().contentType(ContentType.JSON).body(file).post("https://api-int.petco.com:444/accessmanagement-cfa-exp-api/v1/accounts");
        System.out.println(resss);

**Comment by ryreysfo** [comment]
Regards to the original question: I like this solution of using a json file for body input on the post, as shown below. However, I noticed when I use  log() all() the body shown is a path to the file, not the actual content?


    @Test
        public void createPaymentTest() {
    	// Get file from resources folder
    	ClassLoader classLoader = getClass().getClassLoader();
    	File file = new File(classLoader.getResource("payment.json").getFile());
    
    	payment_id = given()
    		.contentType(ContentType.JSON)
    		.auth()
    		.oauth2(accessToken)
    		.when()
    		.body(file)
    		.log()
    		.all()
    		.post("/payments/payment")
    		.then()
    		.log()
    		.all()
    		.extract()
    		.path("id");
    
        }

**Comment by ryreysfo** [comment]
@johanhaleby Regards to the original question: I like this solution of using a json file for body input on the post, as shown below. However, I noticed when I use log() all() the body shown is a path to the file, not the actual content. This works great as is but if I don't have access to the file it might be nice to print out the contents - anyway for me to configure  .log().all() to do this?

@Test
    public void createPaymentTest() {
	// Get file from resources folder
	ClassLoader classLoader = getClass().getClassLoader();
	File file = new File(classLoader.getResource("payment.json").getFile());

	payment_id = given()
		.contentType(ContentType.JSON)
		.auth()
		.oauth2(accessToken)
		.when()
		.body(file)
		.log()
		.all()
		.post("/payments/payment")
		.then()
		.log()
		.all()
		.extract()
		.path("id");

    }
@Styris 
verify your json file is correct see: [JsonViewer](http://jsonviewer.stack.hu/)
verify your path to file is ok, you are using linux type path separator(s) '/'
try doing an ls or dir of that path see if you actually get to the file
looks like you are using IntelliJ, if you are using a maven project try putting your files under src/test/resources and you can use my code above

**Comment by timrsfo** [comment]
@johanhaleby Regards to the original question: I like this solution of using a json file for body input on the post, as shown below. However, I noticed when I use log() all() the body shown is a path to the file, not the actual content. This works great as is but if I don't have access to the file it might be nice to print out the contents - anyway for me to configure .log().all() to do this?

@test
public void createPaymentTest() {
// Get file from resources folder
ClassLoader classLoader = getClass().getClassLoader();
File file = new File(classLoader.getResource("payment.json").getFile());

payment_id = given()
	.contentType(ContentType.JSON)
	.auth()
	.oauth2(accessToken)
	.when()
	.body(file)
	.log()
	.all()
	.post("/payments/payment")
	.then()
	.log()
	.all()
	.extract()
	.path("id");

}
@Styris
verify your json file is correct see: JsonViewer
verify your path to file is ok, you are using linux type path separator(s) '/'
try doing an ls or dir of that path see if you actually get to the file
looks like you are using IntelliJ, if you are using a maven project try putting your files under src/test/resources and you can use my code above

**Comment by timrsfo** [comment]
@johanhaleby Regards to the original question: I like this solution of using a json file for body input on the post, as shown below. However, I noticed when I use log() all() the body shown is a path to the file, not the actual content. This works great as is but if I don't have access to the file it might be nice to print out the contents - anyway for me to configure .log().all() to do this?
    
    @test
    public void createPaymentTest() {
    // Get file from resources folder
    ClassLoader classLoader = getClass().getClassLoader();
    File file = new File(classLoader.getResource("payment.json").getFile());
    
    payment_id = given()
    .contentType(ContentType.JSON)
    .auth()
    .oauth2(accessToken)
    .when()
    .body(file)
    .log()
    .all()
    .post("/payments/payment")
    .then()
    .log()
    .all()
    .extract()
    .path("id");
    
    }
    
@Styris
verify your json file is correct see: JsonViewer
verify your path to file is ok, you are using linux type path separator(s) '/'
try doing an ls or dir of that path see if you actually get to the file
looks like you are using IntelliJ, if you are using a maven project try putting your files under src/test/resources and you can use my code above

**Comment by Styris** [comment]
Thanks @timrsfo it was a problem wherein rest assured was automatically adding a charset type to the content-type so that had to be removed. In any case..can you provide me the code for the original method you are calling? 
Also have you tried to use the filepath right before the extract command to see if that works?
I wasn't sure why you thought I was on Linux.

**Comment by a4aneel** [comment]
Thanks @johanhaleby 

your solution has worked for me

**Comment by akgupta0304** [comment]
String payload = new String(Files.readAllBytes(Paths.get(FilePath/fileName.json)));
		 rs = RestAssured.given().
				 config().
		         headers().
		         body(payload).
		         queryParams().
		         pathParams().
                           post("url");
