### ISSUE TITLE
Add decoding to RequestLoggingFilter

### ISSUE THREAD

**Issue by RocketRaccoon** [jayway/rest-assured#678]
It would be very useful to add decoding of URL in request log by default e.g.
RequestLoggingFilter#filter
```java
	public Response filter(FilterableRequestSpecification requestSpec, FilterableResponseSpecification responseSpec, FilterContext ctx) {
		try {
			RequestPrinter.print(requestSpec, requestSpec.getMethod().toString(), URLDecoder.decode(requestSpec.getURI(), "UTF-8"), logDetail, stream, shouldPrettyPrint);
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
		return ctx.next(requestSpec, responseSpec);
	}
```

**Comment by johanhaleby** [comment]
I see your point but the purpose of this logging is so that one can see more precisely what the generated URI actually looks like.

**Comment by RocketRaccoon** [comment]
So may be it could be additional option for configuring request logger?

**Comment by johanhaleby** [comment]
Good idea, we could make it configurable from the LogConfig.

**Comment by johanhaleby** [comment]
I've now deployed a new snapshot that should address this issue. Please try version `2.8.1-SNAPSHOT` after having added the following Maven repository:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

You can then configure the `com.jayway.restassured.config.LogConfig#urlEncodeRequestUri(..)` like this:

```java
given().config(RestAssured.config().logConfig(logConfig().urlEncodeRequestUri(false)).log().all(). ...
```

Please try it out.

**Comment by RocketRaccoon** [comment]
Hi, working in such way `RequestLoggingFilter(LogDetail.ALL, true, new ReportPrinter("Request..."), false)` works as expected, thanks. When do you plan to release?
