### ISSUE TITLE
RA parsing string incorrectly

### ISSUE THREAD

**Issue by Ameenota** [jayway/rest-assured#682]
String p = "${@print}";
       given().get(p).then();

Gives me:
       java.lang.IllegalArgumentException: Invalid number of path parameters. Expected 1, was 0. Undefined path parameters are: @print\.

This comes from here:
            com.jayway.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1596)

Curl (or Postman) don't seem to mind this.

**Comment by johanhaleby** [comment]
For these cases you need to manually perform URL encoding for your string before passing it to RA. RA treats everything inside curly braces to be parameters (and this is by design).

**Comment by serhatozdursun** [comment]
Hello,
I tried this, but this time the service return 404.
