### ISSUE TITLE
Multiple pathParams don't work with non-standard url path

### ISSUE THREAD

**Issue by tvelykyy** [jayway/rest-assured#683]
Following code will throw exception:
`... when().get("/search;{criteria}={value}", "name", "John") ...`

`java.lang.IllegalArgumentException: Path parameters were not correctly defined. Undefined path parameters are: value.
`
Meanwhile, next code works ok (difference in slash and equals sign):
`... when().get("/search;{criteria}/{value}", "name", "John") ...`

Update. And also this code works:
`... when().get("/search;{c}={value}", "name", "John") ...`

**Comment by johanhaleby** [comment]
Looks like a bug indeed. Thanks for reporting.

**Comment by johanhaleby** [comment]
This was a very specific bug. It only manifested itself when one had defined multiple templates between subresources in the request path or (as in your case) when one had multiple templates after the last `/` IF at the same time the template name was longer than the template value. I've now deployed a new snapshot that should address this issue. Please try version `2.9.1-SNAPSHOT` after having added the following Maven repository:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```
