### ISSUE TITLE
Verifying xmlns URI

### ISSUE THREAD

**Issue by mikejramsey56** [jayway/rest-assured#688]
Given

    <?xml version="1.0" encoding="utf-8"?>
    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
      <soapenv:Body>
        <ns1:getBankResponse xmlns:ns1="http://thomas-bayer.com/blz/">
          <ns1:details>
            <ns1:bezeichnung>ABK-Kreditbank</ns1:bezeichnung>
            <ns1:bic>ABKBDEB1XXX</ns1:bic>
            <ns1:ort>Berlin</ns1:ort>
            <ns1:plz>10789</ns1:plz>
          </ns1:details>
        </ns1:getBankResponse>
      </soapenv:Body>
    </soapenv:Envelope>

How do I verify that 

    xmlns:ns1 == "http://thomas-bayer.com/blz/"

?

**Comment by mikejramsey56** [comment]
See this Stackoverflow [question](http://stackoverflow.com/questions/36941776/verifying-an-xml-attribute-using-jayways-rest-assured/36944525#36944525).

**Comment by johanhaleby** [comment]
I've answered the stackoverflow question and deployed a new snapshot that should address this issue. Please try version `2.9.1-SNAPSHOT` after having added the following Maven repository:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

Please tell me if it doesn't work and I'll reopen the issue.

**Comment by mikejramsey56** [comment]
Works as advertised. Thank you again.
