### ISSUE TITLE
Testing Content Type application/pdf

### ISSUE THREAD

**Issue by ysnikitin** [jayway/rest-assured#690]
Using latest RestAssured 2.8.0.

I have something like this:

`            ValidatableResponse response =
                     given()
                            .contentType('application/pdf')
                            .when()
                            .get(url)
                            .then()
                            .statusCode(200);`

If i do contentType("application/pdf") or not, I get this error:

`java.lang.IllegalStateException: Expected response body to be verified as JSON, HTML or XML but content-type 'application/pdf' is not supported out of the box.
Try registering a custom parser using:
   RestAssured.registerParser("application/pdf", <parser type>);`

I try to register it:

RestAssured.registerParser("application/pdf", Parser.TEXT) or whatever, and I get the same errors.

I cannot write my own Parser since Parser is an enum and cannot be extended.

Is there any way to at least get the call to succeed and then later check the content type? Or can I correctly implement my own parser for pdf content type? Or is there another solution? Thanks!

**Comment by johanhaleby** [comment]
Is this really all the code the you have? Do you do anything with the `response`?

**Comment by ysnikitin** [comment]
You can close this.

To anyone else reading this, you can do this:

String contentType = response.extract().header("Content-Type");
Assert.assertEquals(contentType, "application/pdf"));
